### ISSUE TITLE
cancel 时只看到 原始的数据回滚，其他的数据并没有回滚

### ISSUE THREAD

**Issue by yikangfeng** [changmingxie/tcc-transaction#10]
比如，一个转账事务，在cancel 时，只看到转出转账的数据修改回去了，转入的数据并没有修改回去。

请问是什么原因呢？

**Comment by fuzhq** [comment]
估计是你转入那个服务没有配置好，我测了一下可以正常处理

**Comment by yikangfeng** [comment]
你有QQ吗？我的意思是说比如转账，转出的 还原的，转入的，我看代码里面并没有还原的代码呢？












在 2016-06-02 17:33:55，"fuzhq" <notifications@github.com> 写道：


估计是你转入那个服务没有配置好，我测了一下可以正常处理
