### ISSUE TITLE
支持spring-cloud么

### ISSUE THREAD

**Issue by dounine** [changmingxie/tcc-transaction#102]

**Comment by bbaiggey** [comment]
tcc-transaction不和底层使用的rpc框架耦合，也就是使用doubbo,thrift,web service,http等都可

**Comment by cai3178940** [comment]
spring-cloud中如何传递TransactionContext参数

**Comment by cgnq** [comment]
能否整个例子，大家参考一下。

**Comment by cgnq** [comment]
@cai3178940 TransactionContext传过去了么？我也遇到这个问题。

**Comment by zhengg1492** [comment]
@cai3178940  把TransactionContext序列化成json字符串就行了，比如用阿里的 fastjson
` String transactionContextJson = JSON.toJSONString(transactionContext);
TransactionContext transactionContext = JSON.parseObject(transactionContextJson,TransactionContext.class);`

**Comment by OomelodyoO** [comment]
@cgnq spring-cloud 成功了吗

**Comment by HasonHuang** [comment]
我写了一个与`Spring Cloud`整合的例子，欢迎指正
https://github.com/HasonHuang/distributed-transaction-process

**Comment by ahexian** [comment]
@cai3178940 TransactionContext 是框架自动传递的，你不能进行干预，tcc-transaction不和底层使用的rpc框架耦合。

**Comment by ahexian** [comment]
@cai3178940  
  1. 主事务不能加 TransactionContext 形参,  必须加 @Compensable
  2. 消费端必须加 TransactionContext 形参,  不能加 @Compensable
  3. 供应端必须加 TransactionContext 形参,  必须加 @Compensable
  4. 主事务、消费端、供应端 都必须交给Spring管理
  5. 主事务的try、confirm、cancel都要实现幂等性
  6. 供应端的try、confirm、cancel都要实现幂等性

**Comment by ahexian** [comment]
@cai3178940  
tcc-transaction框架: 
  01. 主事务不能加 TransactionContext 形参, 且必须加 @Compensable
  02. 消费端必须加 TransactionContext 形参, 且不能加 @Compensable
  03. 供应端必须加 TransactionContext 形参, 且必须加 @Compensable
  04. 主事务、消费端、供应端 都必须交给Spring管理
  05. 主事务、消费端、供应端 应该控制在 Service 层
  06. 主事务的try、confirm、cancel都要实现幂等性
  07. 供应端的try、confirm、cancel都要实现幂等性
  08. 必须配置事务补偿定时任务
  09. 补偿次数超过最大尝试次数的不完整事务,要么人工处理,要么修改尝试次数让tcc-transaction重新进行尝试
  10. 补偿超时的不完整事务,要么人工处理,要么修改修改时间让tcc-transaction重新进行尝试
  11. 综合09和10, 最好提供人工干预的接口来进行重试
  12. tcc-transaction 是使用Spring AOP实现的, 不与底层使用的rpc框架耦合,dubbo、Spring Cloud都可以进行整合
