### ISSUE TITLE
使用tcc-trasaction遇到的疑惑

### ISSUE THREAD

**Issue by xuxifu** [changmingxie/tcc-transaction#103]
楼主：
您好，我现在使用的是1.2.3版本。使用中有遇到问题望解答。

是这样的，我在使用的时候通过consumer service A 调用provider service B ，在 B（B的主业务写在B的try方法里，所以执行完B 的try方法后B的事务是已经提交了的）执行完后，返回到A的try里，A 继续执行业务逻辑，此时A执行出错，抛出异常，按tcc-transaction的设计，应该是先回滚A再回滚B（当然此时B的事务已经提交不能回滚）然后（有考虑到1.2.x里的delayCancelExceptions）执行A的cancel方法再通过transactionContextEditor、transactionContext、invocationContext等获取到B的cancel方法并执行（这个逻辑应该是对的吧？）。但是测试的结果发现当执行完A的cancel方法后却没调到B的cancel而是B的try。是我哪里不对吗？。。。。。求解答

**Comment by changmingxie** [comment]
@xuxifu 应该是哪里配置有问题了，可以参考使用指南https://github.com/changmingxie/tcc-transaction/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%971.2.x。如果不是使用dubbo隐式传参方式的话，检查下是不是下面的设置不对：
本地服务通过远程tcc服务提供的client来调用，需要将这些tcc服务的client声明为可加入到TCC事务中，如tcc服务的client方法明为tryXXX,则需要在方法tryXXX上加上如下配置：

@Compensable(propagation = Propagation.SUPPORTS, confirmMethod = "tryXXX", cancelMethod = "tryXXX", transactionContextEditor = MethodTransactionContextEditor.class)

其中propagation = Propagation.SUPPORTS表示该方法支持参与到TCC事务中。 如果tcc服务的client为框架自动生成实现（比如代理机制实现）不能添加注解，可为该client实现一个代理类，在代理类的方法上加上注解。

**Comment by xuxifu** [comment]
您好，看了您的解答，非常感谢。但是，我在provider和consumer都配置了你说的配置，只是provider配置的是required而不是support,除了这个，其他的都有配置。我想，这应该是会影响的吧？
