### ISSUE TITLE
捕捉到异常后在"TCC_Transaction_xxx"表里的的数据VERSION无限增大？

### ISSUE THREAD

**Issue by kson34** [changmingxie/tcc-transaction#105]
我用的是1.1.5，在捕捉到异常后在"TCC_Transaction_xxx"表里的的数据VERSION无限增大都过几万了，并且LAST_UPDATE_TIME也是最新的时间，RETRIED_COUNT是31。但为什么VERSION会无限增大？是不是还在一直RETRIED？这些数据都一周了还在UPDATE。请问是不是BUG还是说是我的误解？

**Comment by kson34** [comment]
好像要更新到1.1.6.4最新版就能解决。

**Comment by changmingxie** [comment]
@kson34 嗯，新版本fixed了。
