### ISSUE TITLE
一个应用部署在多台机器上，它的恢复策略要怎样设置呢？

### ISSUE THREAD

**Issue by chenzqcju** [changmingxie/tcc-transaction#106]
@作者，一个应用部署在多台机器上，一个数据库记录所有事务记录。所有机器的恢复定时器都会去请求数据库，这样是会有问题的，这种情况要怎样设置呢？

**Comment by changmingxie** [comment]
@chenzqcju 所有机器的恢复定时器都会去请求数据库，只有一个请求会生效，原理是根据版本号来做乐观锁控制。
