### ISSUE TITLE
可以集成在非spring项目上吗

### ISSUE THREAD

**Issue by goonover** [changmingxie/tcc-transaction#108]
这个项目的tcc事务管理主要是通过spring的aop来实现的，但是我想把它用在一个最原始的j2se项目里面，应该怎么设置呢？也就是说怎么让tcc-spring起作用，我已经按照教程说的步骤添加tcc-transaction.xml，然而用-verbose调试，切面似乎不起作用

**Comment by changmingxie** [comment]
@goonover 还没有在非spring项目上实践过呢，spring基本上大多数项目都会用到，所以主要是使用了spring的aop来实现。

**Comment by lindengCm** [comment]
> 这个项目的tcc事务管理主要是通过spring的aop来实现的，但是我想把它用在一个最原始的j2se项目里面，应该怎么设置呢？也就是说怎么让tcc-spring起作用，我已经按照教程说的步骤添加tcc-transaction.xml，然而用-verbose调试，切面似乎不起作用

goonover，您好，我这边也有一个非spring的项目，我想问一下，您这边是怎么解决的
