### ISSUE TITLE
关于datasource注入问题

### ISSUE THREAD

**Issue by fuzhq** [changmingxie/tcc-transaction#11]
您好，参考您这个tcc项目，感觉质量还是非常高的。遇到一个问题：JdbcTransactionRepository这个类里面datasource没有注入成功，我是通过直接初始化实现的，求解。
另;FileSystemTransactionRepository、RedisTransactionRepository、ZooKeeperTransactionRepository这几个数据源是怎么应用的呢？感谢！

**Comment by changmingxie** [comment]
@fuzhq 
你好～，可以参考tcc-transaction-dubbo-order项目里的配置，在appcontext-service-datasource.xml中：
<bean id="orderDataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"
          destroy-method="close" lazy-init="false">
        <property name="driverClass" value="#{jdbc['jdbc.driverClassName']}"/>
        <property name="jdbcUrl" value="#{jdbc['jdbc.url']}"/>
        <property name="user" value="#{jdbc['jdbc.username']}"/>
        <property name="password" value="#{jdbc['jdbc.password']}"/>
        <property name="initialPoolSize" value="#{jdbc['c3p0.initialPoolSize']}"/>
        <property name="minPoolSize" value="#{jdbc['c3p0.minPoolSize']}"/>
        <property name="maxPoolSize" value="#{jdbc['c3p0.maxPoolSize']}"/>
        <property name="acquireIncrement" value="#{jdbc['c3p0.acquireIncrement']}"/>
        <property name="maxIdleTime" value="#{jdbc['c3p0.maxIdleTime']}"/>
        <property name="checkoutTimeout" value="#{jdbc['c3p0.checkoutTimeout']}"/>
    </bean>
在appcontext-service-dao.xml中：
 <bean id="transactionRepository"
    class="org.mengyun.tcctransaction.spring.repository.SpringJdbcTransactionRepository">
    <property name="dataSource" ref="**orderDataSource**"/>
    </bean>
另外一个问题：FileSystemTransactionRepository 适合事务提供方节点或是事务调用方是单节点场景，RedisTransactionRepository、ZooKeeperTransactionRepository和JdbcTransactionRepository适合事务提供方节点或是事务调用方节点是多个节点场景（集群），在tcc-transaction-unit-test项目里的tcc-transaction-unit-test.xml中有这些repository的配置示例，在运行时只需要配置一个，如下：

    <context:component-scan base-package="org.mengyun.tcctransaction.unittest"/>


    <bean class="org.mengyun.tcctransaction.spring.recover.DefaultRecoverConfig">
        <property name="maxRetryCount" value="30"/>
        <property name="recoverDuration" value="5"/>
        <property name="cronExpression" value="0/15 * * * * ?"/>
    </bean>

    <bean id="transactionRepository"
          class="org.mengyun.tcctransaction.spring.repository.SpringJdbcTransactionRepository">
        <property name="dataSource" ref="dataSource"/>
    </bean>

    <bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource"
          destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://127.0.0.1:3306/test"/>
        <property name="username" value="root"/>
        <property name="password" value=""/>
    </bean>
