### ISSUE TITLE
如何跟踪查看confirm和cancel方法已经生效

### ISSUE THREAD

**Issue by chentianhui** [changmingxie/tcc-transaction#111]
我在采用springboot改造您的demo，发现confirm和cancel方法不进入，想知道大概什么原因

**Comment by YunaiV** [comment]
建议去尝试调试源码。

本人在写的[《TCC-Transaction 源码解析》](http://www.iocoder.cn/categories/TCC-Transaction/?github)

希望对你有所帮助
