### ISSUE TITLE
如何改进性能

### ISSUE THREAD

**Issue by happycodefromzero** [changmingxie/tcc-transaction#113]
@changmingxie ，我使用自带的HTTP例子，去掉Sleep代码和业务代码，单次执行PlaceOrder（毫无压力）的时间也需要1秒左右，如何做能改进性能到几十毫秒级别？

**Comment by changmingxie** [comment]
@happycodefromzero 可以使用RedisTransactionRepository来存储事务日子, 另外可以设置confirm或cancel是异步执行，不会影响事务的一致性（可获取1.2.3.6版本，@Compensable属性增加了asyncConfirm,asyncCancel属性，可以查看tcc-transaction-http-order例子）

**Comment by happycodefromzero** [comment]
太好了，asyncConfirm,asyncCancel是不是只用在事务发起方设置就可以了？

**Comment by changmingxie** [comment]
@happycodefromzero 可以

**Comment by happycodefromzero** [comment]
@changmingxie 测试了两天，观察到在压力上升的情况下，响应时间会直线上升，例如A -> B 和 C,一开始B和C的响应时间都只有20-30ms，后面压力大了之后，急剧上升为1200-1500ms，视乎存在锁或某种限制降低了并发性能；数据库用的是MySQL，没有将压力增加到瓶颈那么高

**Comment by changmingxie** [comment]
@happycodefromzero 你用asyncConfirm = true么？

**Comment by happycodefromzero** [comment]
加了

**Comment by bwzhang2011** [comment]
@happycodefromzero , 现在情况怎么样了

**Comment by shijiaoming** [comment]
@happycodefromzero 现在情况怎么样了？

**Comment by shijiaoming** [comment]
所以我觉得，这种资源控制，最好还是放到redis（持久化）以及 MongoDB中。
本来tcc的库也是独立的，并且已经适配了MongoDB
