### ISSUE TITLE
FileSystemTransactionRepository不支持windows么?

### ISSUE THREAD

**Issue by hanbin** [changmingxie/tcc-transaction#114]
使用FileSystemTransactionRepository做事务存储, 同样的修改路径, 在mac下可以, 在windows下一直提示找不到文件.
`@Bean
    public TransactionRepository transactionRepository(){
        FileSystemTransactionRepository transactionRepository = new FileSystemTransactionRepository();
        transactionRepository.setRootPath("/Users/icer/IdeaProjects/spring-cloud-practice-refactor/consumer/tcc"); //windows上同样使用绝对路径到这个地方
        return transactionRepository;
    }`

**Comment by changmingxie** [comment]
@hanbin 没有在windows上测试过<_>

**Comment by hanbin** [comment]
@changmingxie 那有可能不支持windows，mac上跑起来是ok的。另外，如果使用redis作为事务存储，如果redis出问题，不能用了。会有默认方案去存储事务么？
