### ISSUE TITLE
dubbo的例子中TCC三个阶段的处理与网上的理论貌似不一致？

### ISSUE THREAD

**Issue by wukonggg** [changmingxie/tcc-transaction#118]
具体疑问如下如下：

### 理论
![17-47-23](https://user-images.githubusercontent.com/10458950/31803683-bd92cf82-b587-11e7-9f42-d479d987a32a.jpg)

### dubbo的例子
比如：PaymentServiceImpl.makePayment()中代码是真正执行的业务：order.pay, updateorder，还调用服务capital和redpacket？如果进入capital的服务CapitalTradeOrderServiceImpl.record()看也是一样的。

try阶段直接就做了持久化更新操作。TRY不是应该检查一致性并预留业务资源吗？
confirm阶段才应该真正执行业务啊。

我看了源码，也看了网上程立的PPT还有其他一些文章，但还是不太明白。所以请教一下，谢谢。

**Comment by xiaoxuliu123** [comment]
扣减资金和红包就是预留资源啊！！！
看扣减资金和红包是否成功就是检查一致性啊！！！

**Comment by wukonggg** [comment]
@xiaoxuliu123 是这个意思啊。。那是我没理解这个业务。谢谢你啦~
