### ISSUE TITLE
dubbo的sample中confirm阶段redpacket当掉后整个case仍然跑完了，这是为什么？

### ISSUE THREAD

**Issue by wukonggg** [changmingxie/tcc-transaction#119]
目标：测试运行dubbo的sample。
思路：在confirm阶段把RedPacket停掉，看系统的数据的变化。
方法：通过debug把RedPacketTradeOrderServiceImpl.confirmRecord()方法debug住，然后手动停该服务的tomcat。
结果：是这样操作以后整个case好像还是跑完了。capital和redpacket的account该加的加该减旳减。

请问有没有人知道这是为什么？ 是我测试的方法不对么？还是什么问题？

感谢！

![tim 20171024092200](https://user-images.githubusercontent.com/10458950/31920642-d8054062-b89c-11e7-9a21-1b923c3e585e.png)

**Comment by wukonggg** [comment]
为什么redpacket的服务都停了，case还能成功执行？

**Comment by changmingxie** [comment]
@wukonggg 看你是怎么停的，有可能停了后，在进程关掉前，没有执行完的请求还会执行

**Comment by wukonggg** [comment]
@changmingxie 我是debug到confirm的入口的，程序在断点的地方后，直接关掉tomcat。断点还在，应该不会继续运行后续代码啊

**Comment by changmingxie** [comment]
@wukonggg 关掉应该还是会执行的，你可以打log看看

**Comment by wukonggg** [comment]
@changmingxie 确实会执行。我后来又尝试了不是debug然后停掉tomcat，而是直接抛出异常。应用会一直尝试继续执行confirm方法。这就是TCC的confirm必须成功，不成功就重试指定次数，重试再不行否则就人工处理吧。
