### ISSUE TITLE
关于改造成通用全局事务的思路设想

### ISSUE THREAD

**Issue by wuzunqian** [changmingxie/tcc-transaction#122]
如果在confirm阶段自动调用本地事务的提交， 在cancel阶段自动调用本地事务的rollback，是否就可以将当前框架改造成类似jta全局事务的通用分布式事务框架， 可以对业务代码透明

**Comment by changmingxie** [comment]
@wuzunqian 设计初衷 是面向服务，服务里可以没有本地事务。
