### ISSUE TITLE
关于 tcc-transaction-dubbo-sample 这个例子中的问题，一个事务跨了多个数据库分片

### ISSUE THREAD

**Issue by zlywq** [changmingxie/tcc-transaction#124]
关于 tcc-transaction-tutorial-sample\tcc-transaction-dubbo-sample，例子代码未能正常运行，只是看了一下其中的代码。
发现一个问题，我认为某处数据库的事务使用有bug。
在 CapitalTradeOrderServiceImpl 里面，看 record()和confirmRecord() 函数。
    它们都对 TradeOrder 和 CapitalAccount 进行了写操作。
    除了对同一条 tradeOrder 进行了写操作，还分别对 transferFromAccount 和 transferToAccount 进行了写操作。
    在分库的情况下，这两条CapitalAccount数据一般不在同一个分库里面。
    那么 tradeOrder 至少与一条CapitalAccount数据不在同一个分库里面。
    而要把它们放在一个事务中，则是不对的。
    如果作者只是用简化代码来示意框架的用法，是没关系的。但是这点最好引起注意。

**Comment by changmingxie** [comment]
@zlywq 只是示例啊
