### ISSUE TITLE
使用TCC-TRANSACTION的公司如果方便请留下公司和网址信息，谢谢！

### ISSUE THREAD

**Issue by changmingxie** [changmingxie/tcc-transaction#129]
可加微信changmingxie, 并说明，如果有bug修复等，会第一时间通知。

**Comment by kaitezhan** [comment]
还在看

**Comment by zhengg1492** [comment]
21cn的流量产品:流量宝 http://nb.189.cn，准备使用，还在测试阶段

**Comment by changmingxie** [comment]
@zhengg1492  你使用的是什么版本，推荐使用KryoPoolSerializer看看

**Comment by lindaosong** [comment]
个人学习，@changmingxie @zhengg1492 我用的也是springcloud继承的，使用KryoTransactionSerializer序列化会错误，错误内容暂时发现的是eureka客户端，使用KryoPoolSerializer可以正常序列化，对ryo的使用不了解，后面再看看
