### ISSUE TITLE
分布式事务发起问题

### ISSUE THREAD

**Issue by Yaccc** [changmingxie/tcc-transaction#13]
在demo#`PlaceOrderServiceImpl`类中，调用两个RPC接口，没有发现有相关的分布式事务发起的动作。在具体配置中也没有具体的说明！望解答！

**Comment by changmingxie** [comment]
@Yaccc 你好，tcc-transaction是使用aop机制拦截方法调用来发起事务; 在tcc-transaction.xml中定义了
 <bean id="tccCompensableAspect" class="org.mengyun.tcctransaction.spring.TccCompensableAspect">
        <property name="compensableTransactionInterceptor" ref="compensableTransactionInterceptor"/>
    </bean>
TccCompensableAspect将拦截在方法上加了Compensable注解的方法来启动事务。
