### ISSUE TITLE
定时恢复事务的job，如果在多台服务器的情况下，会不会有并发问题？

### ISSUE THREAD

**Issue by mmc173168** [changmingxie/tcc-transaction#131]
定时恢复事务的job，如果在多台服务器的情况下，会不会有并发问题？比如多台机器同一时刻都去db中进行需要恢复的事务的检索，然后都执行恢复。

**Comment by changmingxie** [comment]
@mmc173168 恢复job对每个日志 通过乐观锁来处理并发问题，只有一个节点可以操作成功。

**Comment by xuyang0902** [comment]
乐观锁 应该不能控制住并发的问题

**Comment by stackvoid** [comment]
@xuyang0902 并发其实利用由数据库 update 乐观锁来控制的。同一时刻，只能有一个成功更新状态；
update后，即使再去调用 confirm 去提交，幂等性保证不会出现问题，即 confirm 多次也能保证数据的一致性。

@changmingxie 我有个问题：不去update version 岂不是也能正常运行？因为异常事务本来发生概率就低，定时任务无非多执行几次 confirm或 conceal 而已？

**Comment by quaider** [comment]
我也觉得乐观锁不能控制住并发的问题，举个极端的例子，假如`transaction.commit()`卡住了1分钟，定时任务在此期间可能多次加载到了同一个job，并且都很快运行到`transaction.commit()`，这会导致commit执行多次的

**Comment by changmingxie** [comment]
confirm cancel需要保持密等



在 2020-03-14 22:16:08，"Quaider Zhang" <notifications@github.com> 写道：

我也觉得乐观锁不能控制住并发的问题，举个极端的例子，假如transaction.commit()卡住了1分钟，定时任务在此期间可能多次加载到了同一个job，并且都很快运行到transaction.commit()，这会导致commit执行多次的
