### ISSUE TITLE
TCC事务的执行流程

### ISSUE THREAD

**Issue by zqhxuyuan** [changmingxie/tcc-transaction#132]
整理了下流程，发现嵌套调用有点绕，不知道对不对 @changmingxie 。LZ有时间整理个时序图出来吗？

约定：

1. 根事务/本地事务（P1=Order），分支事务/远程事务：P2=Capital，P3=Red。
2. 由于远程事务参与到本地事务是通过Proxy的方式，而远程事务本身也有事务。
3. 所以以P2'表示远程的Capital，P3'表示远程的Red。P2和P3表示Proxy。
4. P1、P2、P3、P2'、P3'的@Conpensable注解都定义了confirm和cancel方法
5. P2和P3 Proxy上的注解的confirm和cancel都是record方法
6. 而且P2和P3的事务传播属性为SUPPORTS，即normal类型
7. TCC中的try方法有时候也叫做record方法，confirm方法也叫做commit

具体流程（重点是步骤20）：

1. P1.try begin new Transaction(1)
2. P1 add to Transaction's participants, => P1
3. 调用 P1的真正方法，分别调用两个proxy的record方法 
4. P2.try no transaction
5. P2 add to Transaction(1)'s participants, now: P1|P2
  6. 由于P2 Proxy调用了远程P2'的record方法，所以P2'远程事务开始工作
  7. P2' try propogate new Transaction(2)
  8. P2' add to his Transaction(2)'s participants, now P2'
  9. 调用P2'的真正方法... P2'远程事务的try方法结束
10. P3.try no transaction
11. P3 add to Transaction(1)'s participants, now P1|P2|P3
  12. 由于P3 Proxy调用了远程P3'的record方法，所以P3'远程事务开始工作
  13. P3' try propogate new Transaction(3)
  14. P3' add to his Transaction(3)'s participants, now P3'
  15. 调用P3'的真正方法... P3'远程事务的try方法结束
16. P1所在的事务Transaction(1)有三个参与者，分别是P1|P2|P3，并且P2和P3的try方法都结束了，注意这里的方法结束，表示P2'和P3'的try方法也结束了
17. P1 ROOT Trasaction调用commit方法，分别调用P1,P2,P3的commit方法
18. P1的commit方法会调用confirmMakePayment
19. 再来看P2和P3 Proxy的commit方法
20. P2的commit方法仍然是record方法（约定5），所以继续调用P2'的record方法，只不过这时P2' 
    try方法的状态是CONFIRMING，所以还会调用它自己的commit方法，即调用P2'的confirm方法
21. P3的commit方法仍然是record方法（约定5），所以继续调用P3'的record方法，只不过这时P3' 
    try方法的状态是CONFIRMING，所以还会调用它自己的commit方法，即调用P3'的confirm方法
22. 整个事务完成

我的理解是本地事务和远程事务都有一个Transaction对象。
远程事务要加入到本地事务中是通过Proxy的方式，这样本地事务有三个Participants（包括自己还有两个远程事务的代理）。而远程事务的Transaction对象中只有自己的Participant：

|Transactions|Transaction1|Transaction2|Transaction3|
|--------------|---------------|--------------|--------------|
|Participants| [P1, P2, P3] | [P2'] | [P3']

这里对约定5的解释是：在本地事务中，要远程调用远程事务，只能通过Proxy，而Proxy的confirm和cancel方法都是record方法。这样远程事务在本地事务的不同阶段（CONFIRMING或CANCEL），要进入不同的分支。比如TRY阶段是propogate new transaction，而CONFIRMING阶段则是propogate exist transaction。
同时在CONFIRMING时，还要调用提交方法，这里的提交是远程事务的提交，即调用远程事务的confirm方法。~~只有当所有远程事务的confirm方法都执行完成后，才会调用本地事务的confirm方法。~~

我在代码中加上日志，整理出来的流程如下：

http://img.blog.csdn.net/20171126201328631

图如下：

![1](http://img.blog.csdn.net/20171126195052058)

之前以为只有资金提交、红包提交之后，才会提交订单。但实际情况却发现先提交订单。
所以这里有个疑问是：P1先commit/confirm，如果后续的P2/P3 confirm失败了，那不就有问题了吗.

**Comment by changmingxie** [comment]
@zqhxuyuan  P2/P3 confirm失败了， 恢复job会重试，调用所有没有执行成功的参与者的confirm方法。

**Comment by zhengg1492** [comment]
好像现在confirm失败了，那后续的P2/P3的 confirm 也不会调用，也不会重试
