### ISSUE TITLE
序列化失败的场景

### ISSUE THREAD

**Issue by xpylq** [changmingxie/tcc-transaction#136]
两个场景想请教下：
1.落地事务日志成功，序列化相关的confirm和cancel失败，这种场景没有补偿机制去处理
2.a-b-c的使用场景，b的try失败后，a发起回滚，b在cancel接口中需要自己判断b的自己的try是否执行成功，(try执行失败去cancel和try执行成功去cancel结果完全不一样)，这样看来增加了业务方的代码复杂度。业务方在实现cancel接口的时候需要实现：1.cancel接口的幂等保证,2.try接口资源是否占有成功的检查

**Comment by changmingxie** [comment]
@xpyzh  第1点，序列化相关的confirm和cancel失败，事务日志是try阶段嘛？ 会有补偿的
