### ISSUE TITLE
请问：能否支持非spring项目呢？

### ISSUE THREAD

**Issue by pengwei52** [changmingxie/tcc-transaction#141]
我们自研的rpc框架不使用spring集成那一套，完全就是面向API的服务发布与调用，请问这种能否将tcc这种框架集成进去呢？

**Comment by changmingxie** [comment]
@pengwei52 目前还不能，后面改进

**Comment by lindengCm** [comment]
> 我们自研的rpc框架不使用spring集成那一套，完全就是面向API的服务发布与调用，请问这种能否将tcc这种框架集成进去呢？

彭sir，您好，我向问一下，你们现在用的是哪个tcc的框架，我这边也有几个项目是非spring的
