### ISSUE TITLE
transactionRecovery 分布式事务恢复时的问题

### ISSUE THREAD

**Issue by shijiaoming** [changmingxie/tcc-transaction#149]
假如目前是1主2从的事务。当执行完try阶段后机器断电。再次启动1主2从的应用后，会由transactionRecovery 来恢复事务，也就是3个transactionRecovery同时尝试恢复。
事务恢复是将持久化的主事务重新load出来构造一个transaction对象。
问题来了：
当我们通过反射去调用各方法时，怎么能保证发起调用的transaction是在当时发起事务的应用中呢？
如果不是，反射调用能成功吗?

**Comment by shijiaoming** [comment]
@changmingxie 加微信了。没有通过。麻烦有空解惑一下。

**Comment by xuyang0902** [comment]
所以我觉得recovery的时候  加分布式锁，db悲观锁（这样需要把rollback|commit的业务一起放在一个事务中，配置ip恢复（哪个ip失败了，在哪台ip上，但是这样会带来 发布的问题 万一哪台机器下线了）） 又或者是单台机器走恢复（但是数据量大的情况又怎么办呢）

**Comment by z529192557** [comment]
不需要保证发起调动的transactionn是在当时发起事务的应用中，只要保证自己的业务代码是   “无状态” 且 “幂等 ” 即可

**Comment by z529192557** [comment]
transactionn  会保存事物参与者执行现场的关键上下文信息，包括：目标对象类型，目标对象方法，目标对象参数，transactionRecovery的时候，只需要根据：“目标对象类型” 找到SpringBeanFactory 中的Bean，然后使用“目标对象参数” 反射调用该Bean的“目标对象方法”，所以只需要保证这个Bean的目标方法是无状态且幂等即可

**Comment by qiaofazhan** [comment]
楼主说的问题不存在，请认真阅读源码：我贴下注释


 /**
     * 找出所有执行错误的事务信息
     * @return
     */
    private List<Transaction> loadErrorTransactions() {

        TransactionRepository transactionRepository = transactionConfigurator.getTransactionRepository();

        long currentTimeInMillis = Calendar.getInstance().getTimeInMillis();

        /*
        * 注意：这里的查询只会查找主干事务，分支事务会过滤掉！！！只有主干事务才会进行事务恢复
        * */
        List<Transaction> transactions = transactionRepository.findAllUnmodifiedSince(new Date(currentTimeInMillis - transactionConfigurator.getRecoverConfig().getRecoverDuration() * 1000));

        List<Transaction> recoverTransactions = new ArrayList<Transaction>();

        for (Transaction transaction : transactions) {
        	// 检验记录是否已经被修改（版本校验）
            /*注意：因为在分布式场景中，每个服务实例都有多个，那么这个定时任务job就会在多个服务实例中同时运行；
             *在不进行分片的情况下，如何保证每条记录只能被一个job操作？
             *针对上述问题这里引入了版本校验：修改当前记录的版本（版本+1,version=Verion+1）；
             * 因为修改操作涉及到本地事务（会有数据库加锁），并且修改条件是当前版本（update version=Verion+1 where version=Version），因此只有一个job会修改成功；
             * 只对修改成功的记录做job操作。
            */
            int result = transactionRepository.update(transaction);
            if (result > 0) {
                recoverTransactions.add(transaction);
            }
        }
        
        // 日志输出，调试用
        if (!transactions.isEmpty()){
        	logger.debug("==>loadErrorTransactions transactions size:" + transactions.size());
        }

        return recoverTransactions;
    }
