### ISSUE TITLE
关于confirm出错的问题

### ISSUE THREAD

**Issue by tiantangbuyaowo** [changmingxie/tcc-transaction#151]
你好，我运行了dubbo的demo，在资金的confirm中加了一行int x = 1/0，然后这个资金服务会提交失败，根本就不会再调用后边红包的service了，这个订单就支付失败，但是钱已经扣了，接下来服务会不断尝试资金的confirm，一直报错，然后就算我把资金的confrim修改正确，重新发布，结果只是资金显示成功，订单依然会是支付失败，红包服务未调用，钱扣了，这样貌似是有问题的吧，我debug跑的时候，发现只要在订单中调用了资金的服务，他直接就去执行资金的confirm，然后才会再执行下边的红包service，我一直以为是三个服务的try都执行完了，没问题，再调用各自的confirm，难道不是这样么？

**Comment by tiantangbuyaowo** [comment]
是因为不能debug吗？只要debug模式下运行，就会出现我上边说的问题

**Comment by cgnq** [comment]
是,都执行完,才会confirm,异步提交问题?看一下文档有个异步提交

**Comment by fengpan111** [comment]
我也遇到了同样的问题，请问该怎么解决

**Comment by zyhfight** [comment]
1.2.x版本，运行tcc-transaction-http-sample，和楼主一样人为添加了 double i = 1/0;让confirm阶段报错；最后结果：订单显示支付成功，余额和红包账号钱也都扣了，不过产生的余额订单和红包订单记录都为DRAFT。
tcc框架在confirm/cancel阶段报错，是无法回滚try阶段commit的数据的，会一直重试，直到最大次数，然后需要人工处理。
