### ISSUE TITLE
事务回恢前造成的数据脏读如何处理？

### ISSUE THREAD

**Issue by qianchong** [changmingxie/tcc-transaction#152]
比方我有一个充值的业务，当充值完成后会调用积分模块增加积分，如果在积分模块的提交阶段失败，那么在tcc的框架恢复前的数据脏读问题请问如何解决？

**Comment by qiaofazhan** [comment]
可以考虑在业务模型中增加一个字段tcc_status（值0,1），业务数据过滤时只过滤tcc_status=1的数据。
try方法中修改记录的tcc_status=0，confirm方法中修改记录的tcc_status=1。
当然tcc_status的值类型也可以是其他枚举值，建议和tcc中的枚举类型保持一致（try，confirm，cancle）。

对于异常：confirm方法中只应该（只能）使用try方法中预留的业务资源,业务资源的逻辑判断和业务异常都应该在try方法中做掉。confirm方法中禁止抛业务异常。特殊的查询也应该在try方法中做掉，并通过TransactionContext参数（有附加的map属性）传递到confirm或cancle方法中。


tcc_status代码实例如下：

 @Override
	@Transactional(rollbackFor = Exception.class)
	@Compensable(confirmMethod = "confirmCreditToPointAccountTcc",cancelMethod = "cancelCreditToPointAccountTcc")
	public void creditToPointAccountTcc(TransactionContext transactionContext, String userNo, Integer pointAmount, String requestNo, String bankTrxNo, String trxType, String remark) throws BizException {

		LOG.info("===>creditToPointAccountTcc TRYING begin");
		
		//根据商户编号获取商户积分账户
		RpPointAccount rpPointAccount = rpPointAccountDao.getByUserNo(userNo);
		if (rpPointAccount == null){//如果不存在商户积分账户,创建一条新的积分账户
			rpPointAccount = new RpPointAccount();
			rpPointAccount.setBalance(0);
			rpPointAccount.setUserNo(userNo);
			rpPointAccount.setStatus(PublicEnum.YES.name());
			rpPointAccount.setCreateTime(new Date());
			rpPointAccount.setId(StringUtil.get32UUID());
			rpPointAccountDao.insert(rpPointAccount);
		}
		RpPointAccountHistory rpPointAccountHistory = rpPointAccountHistoryDao.getByRequestNo(requestNo);
		// 幂等判断
		if ( rpPointAccountHistory == null ){//防止多次提交
			rpPointAccountHistory = new RpPointAccountHistory();
			rpPointAccountHistory.setId(StringUtil.get32UUID());
			rpPointAccountHistory.setCreateTime(new Date());
			rpPointAccountHistory.setStatus(PointAccountHistoryStatusEnum.TRYING.name());//消息不可用  tcc状态
			rpPointAccountHistory.setAmount(pointAmount);///积分账户变动额
			rpPointAccountHistory.setBalance(rpPointAccount.getBalance() + pointAmount);
			rpPointAccountHistory.setBankTrxNo(bankTrxNo);//银行流水号
			rpPointAccountHistory.setRequestNo(requestNo);//请求号
			rpPointAccountHistory.setFundDirection(PointAccountFundDirectionEnum.ADD.name());
			rpPointAccountHistory.setTrxType(trxType);
			rpPointAccountHistory.setRemark(remark);
			rpPointAccountHistory.setUserNo(userNo);
			rpPointAccountHistoryDao.insert(rpPointAccountHistory);
		}else if (PointAccountHistoryStatusEnum.CANCEL.name().equals(rpPointAccountHistory.getStatus())){
			//如果是取消的,有可能是之前的业务出现异常问题而取消,那么重试阶段,再将状态更新为TYING状态,而不是重新创建一条
			LOG.info("之前因为业务问题取消后,又重试的{}" , rpPointAccountHistory.getBankTrxNo());
			rpPointAccountHistory.setStatus(PointAccountHistoryStatusEnum.TRYING.name());
			this.rpPointAccountHistoryDao.update(rpPointAccountHistory);
		}
		//添加一条不可用的积分账户流水
		LOG.info("===>creditToPointAccountTcc TRYING end");
	}

	/**
	 *	积分账户增加确认
	 */

	@Transactional(rollbackFor = Exception.class)
	public void confirmCreditToPointAccountTcc(TransactionContext transactionContext, String userNo, Integer pointAmount, String requestNo, String bankTrxNo, String trxType, String remark) throws BizException {

		LOG.info("===>confirmCreditToPointAccountTcc begin");
		//根据请求号获取账户基本流水
		RpPointAccountHistory rpPointAccountHistory = rpPointAccountHistoryDao.getByRequestNo(requestNo);
		// 幂等判断
		if ( rpPointAccountHistory == null  || PointAccountHistoryStatusEnum.CONFORM.name().equals(rpPointAccountHistory.getStatus())){//该笔交易流水已处理过,不需再处理
			return;
		}
		rpPointAccountHistory.setStatus(PointAccountHistoryStatusEnum.CONFORM.name());//tcc状态
		rpPointAccountHistoryDao.update(rpPointAccountHistory);
		RpPointAccount rpPointAccount = rpPointAccountDao.getByUserNo(userNo);//获取用户积分账户
		rpPointAccount.setBalance(rpPointAccount.getBalance() + pointAmount);//增加账户余额
		rpPointAccountDao.update(rpPointAccount);
		LOG.info("===>confirmCreditToPointAccountTcc end");

	}
	
	
	/**
	 *	积分账户增加回滚
	 * @param transactionContext
	 * @param userNo
	 * @param pointAmount
	 * @param requestNo
	 * @param bankTrxNo
	 * @param trxType
	 * @param remark
	 * @throws BizException
	 */
	@Transactional(rollbackFor = Exception.class)
	public void cancelCreditToPointAccountTcc(TransactionContext transactionContext, String userNo, Integer pointAmount, String requestNo, String bankTrxNo, String trxType, String remark) throws BizException {
		LOG.info("===>cancelCreditToPointAccountTcc begin");

		RpPointAccountHistory rpPointAccountHistory = rpPointAccountHistoryDao.getByRequestNo(requestNo);
		// 幂等判断
		if ( rpPointAccountHistory == null  || !PointAccountHistoryStatusEnum.TRYING.name().equals(rpPointAccountHistory.getStatus())){//该笔交易流水已处理过,不需再处理
			return;
		}
		rpPointAccountHistory.setStatus(PointAccountHistoryStatusEnum.CANCEL.name());//tcc状态
		rpPointAccountHistoryDao.update(rpPointAccountHistory);
		LOG.info("===>cancelCreditToPointAccountTcc end");
	}
