### ISSUE TITLE
参照使用指南1.2.x配置之后一直报错数据库连接错误，是不是需要建立TCC的数据库？

### ISSUE THREAD

**Issue by liulaodao** [changmingxie/tcc-transaction#159]
参照使用指南1.2.x配置之后一直报错数据库连接错误，
我看源码里面包含了一些SQL文件，是不是需要建立TCC的数据库？

![1 2 x](https://user-images.githubusercontent.com/37102119/37024169-156fb066-2163-11e8-8612-f3f90fad9cc6.png)

**Comment by liulaodao** [comment]
@changmingxie 烦请作者指导一下，谢谢！

**Comment by chinatoti** [comment]
我也遇到这个问题。
