### ISSUE TITLE
install项目的时候报错，找到本地环境的配置文件，这个配置文件应该是什么样的？

### ISSUE THREAD

**Issue by liulaodao** [changmingxie/tcc-transaction#160]
install项目的时候报错，找到本地环境的配置文件，这个配置文件应该是什么样的？
@changmingxie 希望得到您的帮助
![111111111111111111111](https://user-images.githubusercontent.com/37102119/37072834-647fd32a-21fe-11e8-84f0-992ba0e087a9.png)
![22222222222222222222](https://user-images.githubusercontent.com/37102119/37072839-69981be2-21fe-11e8-8321-555bdf7e2f07.png)

**Comment by dayforward** [comment]
遇到同样问题，求解

**Comment by lyzhb9014** [comment]
在对应路径中添加dev文件夹就可以编译通过
