### ISSUE TITLE
关于事务恢复Job产生脏数据的问题

### ISSUE THREAD

**Issue by zsjnb** [changmingxie/tcc-transaction#163]
@changmingxie  

我使用的是1.1的版本，之前没注意，最近更新到最新版本后发现你修改了要恢复的事务获取逻辑，其中`findAllUnmodifiedSince`查找的是相关事务域的所有事务，下述场景会出现一个问题：

M支付订单 = A给资金账户加款 + B给积分账户加积分。B增加积分的`confirmMethod`方法出现异常，且M主干事务恢复Job达到最大重试次数并提示`recover failed with max retry count,will not try again.`  此后异常消失，B加积分的分支事务恢复Job开始处理，恢复了出错的事务。

整个过程产生了M主干事务脏数据，虽然你增加了下面的逻辑
`if (transaction.getTransactionType().equals(TransactionType.BRANCH)
            && (transaction.getCreateTime().getTime() +
            transactionConfigurator.getRecoverConfig().getMaxRetryCount() *
                        transactionConfigurator.getRecoverConfig().getRecoverDuration() * 1000
            > System.currentTimeMillis())) {
     continue;
}`
但是时间长点分支事务还是会处理的，只留下主干事务脏数据。不明白为什么要做这种处理，原来恢复Job只查询主干事务，来决定是否恢复整个事务，实在恢复不了就人工干预不是更好？

1.2版本不知道有没有此问题

望赐教，谢谢！

**Comment by changmingxie** [comment]
@zsjnb 基于 当 事务处于 confirming状态后，恢复只会 正向恢复，不会回滚的前提，分支事务如果可以自己正向完成，可以自己主动完成，因为其它事务最终都会正向恢复。主事务 达到recover failed with max retry count,will not try again. 后，人工干预，也是做正向恢复，不能rollback.
