### ISSUE TITLE
求支持spring cloud

### ISSUE THREAD

**Issue by shenzhanwang** [changmingxie/tcc-transaction#167]
求支持spring cloud

**Comment by HasonHuang** [comment]
我这里写了一个[简单示例](https://github.com/HasonHuang/distributed-transaction-process/tree/master/tcc-transaction)，有不对的地方麻烦指教一下。
注意：链接给出的是整合TCC框架的示例，若要运行示例，需要下载[完整项目](https://github.com/HasonHuang/distributed-transaction-process)，完整项目包含了其他的分布式事务解决方案示例，只需关注`tcc-transaction`即可。

**Comment by weir2010** [comment]
求支持？？
