### ISSUE TITLE
TRY阶段rpc超时异常，直接走了cancel？

### ISSUE THREAD

**Issue by xuyang0902** [changmingxie/tcc-transaction#170]
这类是不是需要考虑下，这种业务场景有可能try超时了，cancel流程走完之后，然后走了try ？

楼主对于这类场景有没有什么好的解决方案

**Comment by stackvoid** [comment]
@xuyang0902 
delayCancelExceptions 目前只有两类异常：OptimisticLockException异常和SocketTimeoutException异常(这个异常就是你要的异常)。切点执行后如果有异常先判断是不是这两类，是的话 要更新 Transaction；其他情况 回滚。
