### ISSUE TITLE
以下问题有人思考过没

### ISSUE THREAD

**Issue by 15927131968** [changmingxie/tcc-transaction#174]
1、会不会出现执行了try、confirm、cancel方法，而没有写tcc日志，即tcc日志如何保证与业务操作的一致性
2、若tcc日志和业务操作不能保证一致性，是否能恢复数据
3、confirm和cancel方法是不是一定在try方法之后执行

**Comment by changmingxie** [comment]
@15927131968 
1. 不会，会先更新日志，再调用try confirm cancel方法
2. tcc日志会写完后再调用业务操作，业务操作如果异常，恢复job会重试
3. 是的
