### ISSUE TITLE
tcc事务一致性的问题求解

### ISSUE THREAD

**Issue by huhanguang89** [changmingxie/tcc-transaction#175]
![image](https://user-images.githubusercontent.com/25195117/39754419-babcd536-52f4-11e8-80f1-f6ccc923b652.png)
主事务调用takeOutGoodsService的add和save方法，目前如果add方法异常，那么save方法try都不会执行，主方法是可以cancel方法的。如果save方法异常，那么add方法依然进confirm方法，save方法走cancel方法，主方法走cancel。我想要的效果是三个方法一致性，同时cancel，同时confirm，求问如何解决？add方法如下
![image](https://user-images.githubusercontent.com/25195117/39754538-1dd7b442-52f5-11e8-953d-c714b069451d.png)

**Comment by huhanguang89** [comment]
已经知道原理。因为1.2版本不拦截接口里的注解，只拦截实现类的注解，所以少了一轮通过接口把上下文事务set到dubbo的rpcContext里的过程。所以通过代理类可以弥补这一点，这样事务上下文里才会产生provider的参与者。1.2版本里接口可以不加注解。

**Comment by huhanguang89** [comment]
1.1版本因为是通过参数transactionContext拦截的，所以接口上的注解也可以拦截到。目前不太清楚为什么1.2通过类型拦截无法拦截接口，可能跟spring aop的拦截原理有关，aop对于类型的拦截是cglib的，而对于参数的拦截是动态代理的？有时间看下spring aop的拦截原理。

**Comment by Cyanist26** [comment]
> 已经知道原理。因为1.2版本不拦截接口里的注解，只拦截实现类的注解，所以少了一轮通过接口把上下文事务set到dubbo的rpcContext里的过程。所以通过代理类可以弥补这一点，这样事务上下文里才会产生provider的参与者。1.2版本里接口可以不加注解。

你好，我也遇到了这个问题，RpcContext取出来为空，请问最后是怎么解决的？

**Comment by Cyanist26** [comment]
@huhanguang89 你好，我也遇到了这个问题，RpcContext取出来为空，请问最后是怎么解决的？

**Comment by caiyongpan** [comment]
@huhanguang89  我也是碰到此类问题 求解决方案
