### ISSUE TITLE
被调用方try阶段参数验证不通过未执行怎么表达

### ISSUE THREAD

**Issue by Uniman-Su** [changmingxie/tcc-transaction#176]
看了下源代码事务控制是基于异常来做的。但是如果A调用B，B在参数验证的时候认为操作非法，直接return了。A收到B返回的结果后也直接return了。框架这时应该不知道业务实际上没有执行还是会去调用commit吧，这种情况怎么处理？

**Comment by huhanguang89** [comment]
考虑B里面设置一个threadlocal级别的标记，throw异常触发全局rollback，到B里的rollback的时候，根据标记不触发回滚。

**Comment by kmlkirito** [comment]
老哥，B如果参数验证失败直接抛一个自定义异常怎么样

**Comment by Uniman-Su** [comment]
@huhanguang89 B的rollback还和cancel的时候已经是另外一个线程了
@kmlkirito 这种处理方法不优雅啊。这样的话A的调用者还得通过异常来获取这种业务上不允许操作的返回值，感觉好古怪。
