### ISSUE TITLE
dubbo使用非dubbo协议下，客户端执行两次transactionManager.enlistParticipant(participant)

### ISSUE THREAD

**Issue by HowardYi** [changmingxie/tcc-transaction#179]
dubbo在使用非dubbo协议时，客户端调用链中，有两次proxy代理类执行的过程，第一个是reference bean 最外层的代理，第二个是代理其他remote方式的客户端，proxy->执行clusterInvoker->filter chain->proxy(包装hessian proxy等)，这样导致插入两条事务参与方记录

**Comment by cnicy** [comment]
这样存在并发问题，会出现OptimisticLockException。在try阶段异常的话，cancel是回滚不到的。
