### ISSUE TITLE
帐户在record阶段的操作是否需要加锁?

### ISSUE THREAD

**Issue by hzwang2013** [changmingxie/tcc-transaction#18]
CapitalTradeOrderServiceImpl {
    record () {
        capitalAccountRepository.findByUserId() // 读取账户余额
        // 判断余额是否足够
        capitalAccountRepository.save()  // 保存账户余额 - 花费
}
读取账户余额的时候是否需要加锁？
还是有其他机制保证操作的原子性

**Comment by changmingxie** [comment]
@hzwang2013 示例仅仅是一个demo，在真实项目中使用时是必须得考虑的，但不建议在读取账户余额时就加锁，会影响性能吧。建议在更新account时再做一遍余额检查，比如在sqlmap.xml中sql脚本更改如下：
UPDATE
        CAP_CAPITAL_ACCOUNT
        SET
        BALANCE_AMOUNT = BALANCE_AMOUNT+#{transferedAmount}
        WHERE CAPITAL_ACCOUNT_ID = #{id}  AND BALANCE_AMOUNT+#{transferedAmount}>=0;

其中#{transferedAmount}转账金额（可正可负)，如果BALANCE_AMOUNT+#{transferedAmount}不满足>=0，则更新失败，应用程序可提示余额不足等。
