### ISSUE TITLE
请问，tcc-transaction能与sharding-jdbc联用么？

### ISSUE THREAD

**Issue by xiaoyanghapi** [changmingxie/tcc-transaction#181]

**Comment by devpage** [comment]
https://devpage.github.io

**Comment by devpage** [comment]
https://devpage.github.io/#/user/blog/details/dadc208a1e5631ca5e7e549199c72271

**Comment by xiaoyanghapi** [comment]
好的，谢谢，看来是支持了。因为bytetcc的处理方式是代理数据源，所以与sharding-jdbc联用可能有问题，所以直接咨询您了
