### ISSUE TITLE
master1.2.X branch compile fail

### ISSUE THREAD

**Issue by Agent-Tao** [changmingxie/tcc-transaction#182]
tcc-transaction-server can not be compiled，the error log is as follow:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project tcc-transaction-server: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war failed: basedir /Users/jiangtao/IdeaProjects/tcc-transaction/tcc-transaction-server/src/main/config/dev does not exist -> [Help 1]

**Comment by kongspace** [comment]
在pom中把maven-war-plugin插件下的configuration节点注释掉就好了

**Comment by yuboYUBO** [comment]
还有，如果使用的是maven3.6.0的话，这个插件maven-war-plugin:2.1.1 版本有点低，也会报错，需要将版本改成高一点的版本就好了。
