### ISSUE TITLE
求作者解答一下事务恢复的原理

### ISSUE THREAD

**Issue by kongspace** [changmingxie/tcc-transaction#186]
if (transaction.getTransactionType().equals(TransactionType.BRANCH)
                    && (transaction.getCreateTime().getTime() +
                    transactionConfigurator.getRecoverConfig().getMaxRetryCount() *
                            transactionConfigurator.getRecoverConfig().getRecoverDuration() * 1000
                    > System.currentTimeMillis())) {
                continue;
            }
事务恢复中这段代码看不懂，希望作者解答一下整个事务恢复原理

**Comment by runnerFeng** [comment]
http://www.iocoder.cn/TCC-Transaction/transaction-recovery/
