### ISSUE TITLE
tcc-transaction-http-sample 疑问

### ISSUE THREAD

**Issue by robustwang** [changmingxie/tcc-transaction#188]
tcc-transaction-http-sample 模块里的 order 调用capitalTradeOrderService 和redPacketTradeOrderService，代码接口上看，这2个服务并不是和order 分离单独运行的服务，而且代码中直接依赖的，这样不是分布式了吗？

**Comment by shicanLeft** [comment]
在使用spring http invoker 发起远程调用的时候  一直响应404  找不到http 远程暴露的服务 ，请问有遇到过这样的情况吗？

**Comment by runnerFeng** [comment]
@shicanLeft 
consumer端：
 <bean id="redPacketTradeOrderService" class="org.springframework.remoting.httpinvoker.HttpInvokerProxyFactoryBean">
        <property name="serviceUrl" value="http://localhost:8082/remoting/RedPacketTradeOrderService"/>
        <property name="serviceInterface"
                  value="org.mengyun.tcctransaction.sample.http.redpacket.api.RedPacketTradeOrderService"/>
        <property name="httpInvokerRequestExecutor" ref="httpInvokerRequestExecutor"/>
    </bean>

provider端：
 <bean id="httpServer"
          class="org.springframework.remoting.support.SimpleHttpServerFactoryBean">
        <property name="contexts">
            <util:map>
                <entry key="/remoting/RedPacketTradeOrderService" value-ref="redPacketTradeOrderServiceExporter"/>
            </util:map>
        </property>
        <property name="port" value="8082"/>
    </bean>

这个consumer端serviceUrl的值和provider端的配置能不能对上，端口也要注意下啊，还有那个localhost
