### ISSUE TITLE
dubbo 示例中为什么 接口只有 @Compensable注解，没有属性?

### ISSUE THREAD

**Issue by qian-japan** [changmingxie/tcc-transaction#195]
您好，为什么 provider的 接口 只有注解 @Compensable，不用配置confirmMethod = "confirmRecord", cancelMethod = "cancelRecord", 在 事务发起方 调用 远程tcc事务方法时，dubbo代理对象应该只有@Compensable 这个注解吧，是没法拿到 实现类配置的 confirmMethod = "confirmRecord", cancelMethod = "cancelRecord"？不太明白

/**
 * Created by changming.xie on 4/1/16.
 */
public interface CapitalTradeOrderService {

    @Compensable
    public String record(CapitalTradeOrderDto tradeOrderDto);

}

**Comment by changmingxie** [comment]
@qian-japan 这里是做标记

**Comment by mrsWangxing** [comment]
调用 远程tcc事务方法时 没有直接调用 confirm和cancel 而是调用了provider的@Compensable的方法 那个方法里面根据 参数什么的判断出 该调用提供者的confirm或者cancel

**Comment by wukong0503** [comment]
借个楼问一哈 @changmingxie  
confirm的时候，没有走dubbo服务的confirm方法，而还是走的同一个方法
可能的情况是啥，，，我都是按照demo配置的 没差
