### ISSUE TITLE
请问tcc-transcation是否支持分布式事务？

### ISSUE THREAD

**Issue by karonwu** [changmingxie/tcc-transaction#2]
在单节点上表现完美。
请问tcc-transcation是否支持分布式事务，跨节点的？

**Comment by changmingxie** [comment]
当然。本身就是为分布式环境下设计实现的。

**Comment by wuherong** [comment]
你好，我现在建了两个应用，A应用调B应用的两个方法，想做事务控制，可是都是在单独的事务里面。
我改了下这个地方，加了备注，否则不能够注入BeanFactory工厂，不知是否与这个有关，但是去除备注的话，两个应用，对应的BeanFactory很定不是一个，获取Bean的实例，及自动注入就有问题了。如果是一个工程这样倒是可以。不知我的理解是否正确。
public class TccBeanPostProcessor implements ApplicationListener<ContextRefreshedEvent> {

    @Override
    public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
        ApplicationContext applicationContext = contextRefreshedEvent.getApplicationContext();

        //if (applicationContext.getParent() == null) {

            BeanFactoryAdapter.setBeanFactory(applicationContext.getBean(BeanFactory.class));
        //}
    }
}

**Comment by changmingxie** [comment]
@wuherong,
你好，你建的A,B两个应用是部署在不同的节点上的吧(使用不同的JVM)?，如果是部署在不同的节点，那么BeanFactory一定是不同的；
在tcc-transaction-dubbo-sample里示例了3个应用使用tcc-transaction例子，
分别是tcc-transaction-dubbo-order、tcc-transaction-capital、tcc-transaction-redpacket，这三个应用可分别部署在不同节点，希望能对你有帮助。
特别说明下，tcc-transaction.xml一定要加载到classpath中；如在web.xml中：
<context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>classpath:tcc-transaction.xml
        </param-value>
</context-param>
