### ISSUE TITLE
methodType的几种类型分别是什么意思

### ISSUE THREAD

**Issue by aqu415** [changmingxie/tcc-transaction#200]
public enum  MethodType {
    ROOT,
    CONSUMER,
    PROVIDER,
    NORMAL;
}
请问下这个枚举的几个可选值代表什么意思呢？

**Comment by runnerFeng** [comment]
http://www.iocoder.cn/TCC-Transaction/tcc-core/#
参加6.2节，对这个有详细的解释

**Comment by mrsWangxing** [comment]
ROOT    根 可以理解为事务的发起者 会创建一个 Transaction
CONSUMER    根调用服务提供者的接口（消费者 这里面是ROOT一个参与者 会把他加到ROOT的Transaction的参与者列表中去）
PROVIDER,     服务提供者 会创建另一个Transaction
NORMAL;  没太注意
