### ISSUE TITLE
不知道以后是不是提供跟spring boot整合的spring-boot-starter，感谢作者回答

### ISSUE THREAD

**Issue by willenfoo** [changmingxie/tcc-transaction#204]
不知道以后是不是提供跟spring boot整合的spring-boot-starter，感谢作者回答

**Comment by changmingxie** [comment]
@willenfoo 目前没有计划，期待开源社区贡献

**Comment by willenfoo** [comment]
可以，我年底开发试试

**Comment by willenfoo** [comment]
@changmingxie 可以，我年底开发试试

**Comment by xiaobzhou** [comment]
我实现了一下tcc-transaction1.2.x与springboot2.x自动配置和与feign自动集成https://github.com/xiaobzhou/tcc-transaction
