### ISSUE TITLE
关于AOP执行顺序的问题

### ISSUE THREAD

**Issue by liqile1** [changmingxie/tcc-transaction#206]
CompensableTransactionInterceptor
和
ResourceCoordinatorAspect
这俩aspect的执行顺序是怎样的？是在哪些（个）文件中指定的？

**Comment by liqile1** [comment]
up

**Comment by changmingxie** [comment]
CompensableTransactionInterceptor先，ResourceCoordinatorAspect后，可以看看Spring Aop拦截顺序设置

**Comment by z529192557** [comment]
实际上用的是这两个Aspect的子类ConfigurableTransactionAspect 和 ConfigurableCoordinatorAspect，且这两个子类实现了Ordered 接口，order较小的先执行，tcc-transaction-spring下 tcc-transaction.xml中配置
