### ISSUE TITLE
二阶段commit前，更新tcc_log时断电了怎么恢复？

### ISSUE THREAD

**Issue by xuyang0902** [changmingxie/tcc-transaction#207]
org.mengyun.tcctransaction.TransactionManager类

 public void commit(boolean asyncCommit) {

        final Transaction transaction = getCurrentTransaction();

        transaction.changeStatus(TransactionStatus.CONFIRMING);
         
       //这行代码断电了怎么处理啊 老铁？
        transactionRepository.update(transaction);

        if (asyncCommit) {
            try {
                Long statTime = System.currentTimeMillis();

                executorService.submit(new Runnable() {
                    @Override
                    public void run() {
                        commitTransaction(transaction);
                    }
                });
                logger.debug("async submit cost time:" + (System.currentTimeMillis() - statTime));
            } catch (Throwable commitException) {
                logger.warn("compensable transaction async submit confirm failed, recovery job will try to confirm later.", commitException);
                throw new ConfirmingException(commitException);
            }
        } else {
            commitTransaction(transaction);
        }
    }

**Comment by changmingxie** [comment]
@xuyang0902 如果是Root事务更新状态时断电 没有更新状态成功，则恢复job获取事务状态时还是Trying阶段，回执行Cancel操作

**Comment by xuyang0902** [comment]
所以说存在一种可能：try阶段已经全部成功了，这个时候断电，如你所说，应用重启后，恢复job拿到的是trying状态 直接执行cancel操作。。对于一些不太严格的业务确实可以如此操作，但是对于某些严谨的业务，是否可以考虑给一个事务状态的查询器，在这种情况下 查询事务的状态 决定二阶段的走向。

**Comment by kwengelie** [comment]
@changmingxie 我觉得 @xuyang0902 说的有道理。通常交易都是需要同步反馈结果状态的，比如成功、失败、超时、处理中等状态。根据TCC-Transaction框架，交易状态是由try方法反馈的，即try方法反馈成功，则认为交易成功了。而事务恢复时，对于主事务为TRYING状态的交易都是做cancel处理的，即按失败处理。这样是否会造成交易短款？

**Comment by xuyang0902** [comment]
@kwengelie  在那些极端的场景下，交易确实要走退款咯。我借鉴了淘宝之前的dtx和tcc-transaction的思想写了一个组件 目前还未开源，总体来看，添加了对事务恢复的友好处理（多机器恢复支持并行恢复且不浪费机器资源），添加了事务管理后台（监控客户端的状态），断电|异常情况下的严谨业务恢复。

**Comment by kwengelie** [comment]
@xuyang0902 短款之后就不好退款了。我又仔细研究了下这块代码，发现如果update失败，估计做不了commit，也做不了rollback。因为commit和rollback的参数是通过try方法提供的，如果update失败了，那么try方法提供的参数还没有存储到数据库中，这时候commit和rollback如果调用的话，是没有参数值的。 @changmingxie 你看我说的对否？

**Comment by kwengelie** [comment]
@xuyang0902 短款之后就不好退款了。我又仔细研究了下这块代码，发现如果update失败，估计做不了commit，也做不了rollback。因为commit和rollback的参数是通过try方法提供的，如果update失败了，那么try方法提供的参数还没有存储到数据库中，这时候，在事务恢复方法中调用commit和rollback的话，是没有参数值的。 @changmingxie 你看我说的对否？

**Comment by xuyang0902** [comment]
@changmingxie 你可以选择在tcc_transaction之上重构代码，把事务恢复这块修正一下，如果未拿到明确try阶段的状态，通过自己设定的bean去翻查确认事务的最终状态来确认二阶段的提交。

**Comment by xuyang0902** [comment]
@kwengelie update失败 应该也是走的rollback

**Comment by kwengelie** [comment]
问题是：rollback的时候，无法拿到参数值呀。

**Comment by xuyang0902** [comment]
@kwengelie rollback的参数 是在执行try之前就set进去了吧

**Comment by kwengelie** [comment]
@xuyang0902 确实！！！

**Comment by xuyang0902** [comment]
@kwengelie  所以标的存在的那个还是存在的哈哈，楼主回复了 确实是回滚的 所以严谨的业务还得加点代码

**Comment by xuyang0902** [comment]
@changmingxie  举一个例子吧。就好比tcc-transaction设计的delayCancelExceptions。其实对于这个异常的设计我也有点疑问，比如说调用最后一个参与方 网络异常了（参与者可能是执行成功了，也可能是失败了，也可能是处理中）   tcc-transaction 相当于在恢复任务的时候延迟执行了回滚操作。 其实个人认为并不应该是这样的，网络异常在分布式系统中是很常见的。调用方不能仅仅因为网络原因就直接否认了参与者成功执行的结果，所以我认为对于这类异常，还有断电，tcc-transaction可以提供一种选择，编码者可以自己选择是否需要通过查询来决定执行该笔单据的二阶段confirm 或者 cancel操作。而不是统一的做一个cancel。因为复杂业务 一堆T结合在一起也是有很大的成本的。
