### ISSUE TITLE
tcc移植到现有项目 通不过

### ISSUE THREAD

**Issue by momoangu** [changmingxie/tcc-transaction#21]
这一块不太熟。
现有项目不是用maven搭建的；用的是spring  4.0.4,
我现在引入tcc-transaction-spring-1.1.2.jar、tcc-transaction-core-1.1.2.jar、tcc-transaction-api-1.1.2.jar（spring 4.0.4下编译的）以及其他依赖jar包， 按照说明加tcc-transaction.xml,  启动的时候提示
Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tccCompensableAspect' defined in class path resource [tcc-transaction.xml]: Cannot resolve reference to bean 'compensableTransactionInterceptor' while setting bean property 'compensableTransactionInterceptor'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compensableTransactionInterceptor' defined in class path resource [tcc-transaction.xml]: Cannot resolve reference to bean 'tccTransactionConfigurator' while setting bean property 'transactionConfigurator'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tccTransactionConfigurator': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mengyun.tcctransaction.TransactionRepository org.mengyun.tcctransaction.spring.support.TccTransactionConfigurator.transactionRepository; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mengyun.tcctransaction.TransactionRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}；

**Comment by changmingxie** [comment]
@momoangu  看错误提示，你需要配置TransactionRepository，可以参考使用指南里“设置TransactionRepository” https://github.com/changmingxie/tcc-transaction/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

**Comment by momoangu** [comment]
@changmingxie 非常感谢！按照参考指南的配了，目前项目可以跑起来，但有点状况：问题现象跟https://github.com/changmingxie/tcc-transaction/issues/3提到的一样，也是订单始终是PAYING状态，我按帖子里面的解决方案试了，无效；另外：当我把payer方的红包金额改为5的时候，按道理失败；账户不会变动；结果却是payer的红包账户金额变为15了。其他跟进测试中...

**Comment by momoangu** [comment]
@changmingxie 目前遇到新问题了，请帮忙分析。类似order的例子在我的项目中 在支付方 资金账户余额足够但红包账户余额不足的情况下；红包账户调用了cancelMethod 而资金账户却没有调用cancelMethod;  跟踪了一下，发现是调用顺序不是按 
t1: order try make payment called
t4:order confirm make payment called
capital项目：
t2:capital try record called
t5:capital confirm record called
redpacket项目：
t3:red packet try record called
t6:red packet confirm record called
这个模式来的（当然你这里没有列出支付异常的情况）

我这里有两个账户金额如上所述异常的情况下调用顺序是这样的：
capital try record called
capital confirm record called
red packet try record called
red packet cancel record called 


如上 capital 没有到cancelMethod里面去； 请帮忙分析分析原因在哪？

**Comment by changmingxie** [comment]
@momoangu  如果进入confirm状态 是不会调用cancel方法的。 可以运行示例项目看看。

**Comment by momoangu** [comment]
@changmingxie  谢谢！整个流程终于通过了； order照搬到我的项目中， 通过，挺好。接下来消化整理，再次感谢。
