### ISSUE TITLE
源码疑问TransactionRecovery

### ISSUE THREAD

**Issue by BraveWay** [changmingxie/tcc-transaction#212]
TransactionRecovery中的第55行
transaction.getTransactionType().equals(TransactionType.BRANCH)
                    && (transaction.getCreateTime().getTime() +
                    transactionConfigurator.getRecoverConfig().getMaxRetryCount() *
                            transactionConfigurator.getRecoverConfig().getRecoverDuration() * 1000
                    > System.currentTimeMillis())
这段代码是干嘛用的。是说分支事务要经过一定时间后才能恢复吗？

**Comment by mrsWangxing** [comment]
只是一种恢复的策略 恢复时有 恢复的最大尝试次数MaxRetryCount  和恢复的间隔时间RecoverDuration
try成功的事务  就只能一直走下去了 没法回头了 如果恢复的最大尝试次数都是没有办法 把事务走完 只能人工参与了。

**Comment by alexyezhigang** [comment]
我想了解为什么根事务就不用考虑最大重试次数,仅仅此处判断branch?

**Comment by kwengelie** [comment]
@alexyezhigang 个人认为最大重试次数是不能有效控制的，只有时间才能精确控制。原因如下：
关键看业务上对这个问题的敏感程度。通常情况下，只要事务未正常结束，那么结果都已经确定了。
关键在于业务上对得到最终结果有没有强制性要求。

另外，我认为：分支事务根本没必要启动定时事务恢复线程。只有主事务才有启动的必要。所以建议事务中区分主事务和分支事务，恢复时只需要拿主事务进行恢复即可。

if (transaction.getStatus().equals(TransactionStatus.CONFIRMING)) {
                    transaction.changeStatus(TransactionStatus.CONFIRMING);
                    //1、数据库报错后，重试次数未刷新
                    transactionConfigurator.getTransactionRepository().update(transaction);
                    //2、数据库已更新，但是突然断电，实际上未重试
                    transaction.commit();
                    transactionConfigurator.getTransactionRepository().delete(transaction);
                }

**Comment by kwengelie** [comment]
@alexyezhigang 个人认为最大重试次数是不能有效控制的，只有时间才能精确控制。原因如下：
if (transaction.getStatus().equals(TransactionStatus.CONFIRMING)) {
transaction.changeStatus(TransactionStatus.CONFIRMING);
//1、数据库报错后，重试次数未刷新
transactionConfigurator.getTransactionRepository().update(transaction);
//2、数据库已更新，但是突然断电，实际上未重试
transaction.commit();
transactionConfigurator.getTransactionRepository().delete(transaction);
}

关键看业务上对这个问题的敏感程度。通常情况下，只要事务未正常结束，那么结果都已经确定了。
关键在于业务上对得到最终结果有没有强制性要求。

另外，我认为：分支事务根本没必要启动定时事务恢复线程。只有主事务才有启动的必要。所以建议事务中区分主事务和分支事务，恢复时只需要拿主事务进行恢复即可。

**Comment by alexyezhigang** [comment]
@kwengelie 我认为分支事务定时恢复是有必要的，A->B->C,那么B,C都属于分支事务，显然对于A来说，根本不知道C的存在，除非业务规定B的cancel里面一定要调用C的cancel，但这样子就变成了只是松散的约定
