### ISSUE TITLE
版本1.2.4.23中数据库脚本缺少IS_DELETE字段

### ISSUE THREAD

**Issue by xiaochunping** [changmingxie/tcc-transaction#217]
![image](https://user-images.githubusercontent.com/4407539/47290303-5f92d500-d631-11e8-9831-e685188f9d78.png)
这里添加了一个新的条件，但是sql并没有更新。测试samplt dubbo会报错，有时间把sql也更新下。

**Comment by code1986** [comment]
最新的tcc-transaction/tcc-transaction-spring/src/main/dbscripts/db.sql脚本中有加IS_DELETE字段

`
ALTER TABLE `TCC_TRANSACTION` ADD `IS_DELETE` tinyint(1) DEFAULT 0 NOT NULL;
`

**Comment by yuboYUBO** [comment]
> IS_DELETE

在dubbo的sample中没有更新
