### ISSUE TITLE
try阶段可否并行执行(异步)?

### ISSUE THREAD

**Issue by sangyuan6122** [changmingxie/tcc-transaction#218]
测试中两个服务中的try是顺序执行，可否并行呢

**Comment by kwengelie** [comment]
@sangyuan6122 个人觉得try阶段对远程方法的调用的确是可以做成并行执行。关键是看你业务上的依赖关系情况。比如
tryA(){
   rsB= tryB();
    tryC(rsB);
}
这个在框架层面恐怕不是很好控制。
