### ISSUE TITLE
ThreadLocal的使用存在内存泄漏

### ISSUE THREAD

**Issue by kwengelie** [changmingxie/tcc-transaction#219]
在TransactionManager中使用了ThreadLocal，如下：
private static final ThreadLocal<Deque<Transaction>> CURRENT = new ThreadLocal<Deque<Transaction>>();

在CompensableTransactionInterceptor拦截器主事务方法执行完毕后，
transactionManager.cleanAfterCompletion(transaction);
未执行ThreadLocal的remove方法，会导致内存泄漏。

建议：transactionManager.cleanAfterCompletion(transaction)中对ThreadLocal缓冲对象remove下。

**Comment by alexyezhigang** [comment]
刚刚我也提交了类似的问题, 建议修改为：
`public void cleanAfterCompletion(Transaction transaction) {
        if (isTransactionActive() && transaction != null) {
            Transaction currentTransaction = getCurrentTransaction();
            if (currentTransaction == transaction) {
                CURRENT.get().pop();
                if(CURRENT.get().size() == 0){
                    eraseAll();
                }
            } else {
                throw new SystemException("Illegal transaction when clean after completion");
            }
        }
    }`

**Comment by changmingxie** [comment]
@alexyezhigang @ITonyLi 多谢大家，采用alexyezhigang建议。
