### ISSUE TITLE
关于threadlocal的疑问

### ISSUE THREAD

**Issue by alexyezhigang** [changmingxie/tcc-transaction#221]
我发现你在transactionmanager里面创建了ThreadLocal<Deque<Transaction>> CURRENT, 这里我有两个疑问：
1.是否有必要创建queue，因为每次你都是从拦截器获取事务再set进threadlocal，每一次操作都是线程独立的，也就是说我感觉这个queue的元素个数不会超过1
2. 你重来没有调用threadlocal的remove方法，这可能有OOM的危险

**Comment by VainEffort** [comment]
deque看代码应该是用来处理嵌套事务的，如果如果存在REQUIRES_NEW的话。
那个threadlocal清理的代码是在CompensableTransactionInterceptor-->rootMethodProceed-->cleanAfterCompletion
这里

**Comment by code1986** [comment]
确实可以移除Deque

**Comment by VainEffort** [comment]
Deque是用来处理嵌套事务的吧，一个线程内可能存在其他RequiresNew的事务，有个Deque可以逐层处理。
