### ISSUE TITLE
mysql最新版本不支持吗？

### ISSUE THREAD

**Issue by Ifdevil** [changmingxie/tcc-transaction#222]
我本地是mysql 8的版本，项目中依赖的mysql-connctor-java的版本是5.0.11，会报“ Unknown system variable `'tx_isolation'”的错误

**Comment by code1986** [comment]
![image](https://user-images.githubusercontent.com/15826438/48703137-d077dd80-ec2d-11e8-82b9-9d2a19ed527d.png)
Connector/J 对MySQL server的支持情况,你应该升级一下你的mysql-connector-java,至少到5.1
参考下面这个链接
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html

**Comment by zyhfight** [comment]
Mysql版本：8.0.12；mysql-connector-java版本为5.1.33仍然会出现“ Unknown system variable `'tx_isolation'”，升级到8.0.12，问题解决。

**Comment by Ifdevil** [comment]
谢谢

**Comment by Ifdevil** [comment]
> ![image](https://user-images.githubusercontent.com/15826438/48703137-d077dd80-ec2d-11e8-82b9-9d2a19ed527d.png)
> Connector/J 对MySQL server的支持情况,你应该升级一下你的mysql-connector-java,至少到5.1
> 参考下面这个链接
> https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html

谢谢
