### ISSUE TITLE
事务recover定时任务运行时一直报错：IS_DELTE不存在

### ISSUE THREAD

**Issue by mw138** [changmingxie/tcc-transaction#223]
事务recover定时任务运行时一直报错：IS_DELTE不存在，这个问题有人在修复吗

**Comment by ibywind** [comment]
我本地碰到了这个问题 我自己加上了
SQL脚本不是最新的

**Comment by changmingxie** [comment]
@mw138 谢谢，已更新sql scripts

**Comment by wzming** [comment]
@changmingxie cap_trade_order和ord_order表可能还缺失version字段

**Comment by wuhaiyou** [comment]
加了这些字段之后，就能调通了吗？findByShopId取数据报错没遇到吗？
