### ISSUE TITLE
事物参与方cancel方法不执行的问题

### ISSUE THREAD

**Issue by xiaobzhou** [changmingxie/tcc-transaction#228]
你好，请问一下使用dubbo框架，在事物发起方（A服务）调用了事物参与方（B服务），然后手动抛了一个异常，A的cancel方法执行了，B的cancel方法没有执行，数据库有B的事物日志status是1（TRYING），在恢复的时候就啥事没做。

**Comment by changmingxie** [comment]
看看是不是配置是否有问题

**Comment by xiaobzhou** [comment]
@changmingxie 博主你好，为了弄清楚问题原因跟了一下源码，有点不能理解的地方能不能指点一下。
A服务（事物发起方），B服务（事物参与方）
	A服务开始执行CompensableTransactionInterceptor拦截在数据库创建了一条事物日志记录且状态为TRYING，ResourceCoordinatorInterceptor更新事物日志加入一个participant（A服务本身），
	B服务开始执行CompensableTransactionInterceptor拦截在数据库创建了一条新事物日志记录且状态为TRYING，ResourceCoordinatorInterceptor更新事物日志加入一个participant（B服务本身），
	然后在A服务调用B服务调用成功后A服务发生异常，A服务执行rollback，在rollback的时候查询事物日志修改状态为CANCELING执行participants的cancel方法，因为A服务查询的事物日志的participants只有A本身所以A的candel方法执行了，我遇到的问题好像是这么产生的。
       请问一下我跟源码的理解是不是有错，实在是有点蒙了。

**Comment by xiaobzhou** [comment]
请问支持A调B，B调C这种情况吗
