### ISSUE TITLE
两阶段事务的疑问

### ISSUE THREAD

**Issue by renxinlin** [changmingxie/tcc-transaction#235]
两阶段事务：
1第一阶段执行成功了
2第二阶段数据库插入成功了，由于某种原因事务管理器没有收到 
3 事务管理器做了个补偿插入
数据库多了个重复的脏数据，这种问题怎么处理？

**Comment by tubaowang** [comment]
唯一索引？

**Comment by javalanxiongwei** [comment]
你的confirm和cancel需要实现幂等.
