### ISSUE TITLE
无论方法是否抛出异常，均只进入confirm方法，请问这是什么原因？

### ISSUE THREAD

**Issue by pengcgithub** [changmingxie/tcc-transaction#239]
如图所示，无论方法中出现什么异常，均不会进入cancel方法体内，请问这是什么原因？
![tcc-transaction](https://user-images.githubusercontent.com/16138408/52530362-5e4ffa00-2d3f-11e9-8dc4-09683e560eb6.png)

**Comment by pengcgithub** [comment]
上面的问题可能是事物控制放在了controller上面，所有导致了事物失效。请问事物控制能否在controller层监控？

**Comment by VainEffort** [comment]
你异常都吃掉了，外部怎么知道你要回滚啊

**Comment by pengcgithub** [comment]
> 你异常都吃掉了，外部怎么知道你要回滚啊

我有将异常抛出哎！现在的问题是，如果直接在controller层控制，是没有办法处理事务的。相同的写法换到service层是没有问题的。
例如：https://github.com/pengcgithub/platform-dubbo/blob/master/platform-web-user/src/main/java/com/tracy/web/module/user/service/UserServiceMock.java
