### ISSUE TITLE
debug发现数据库订单表没有尽经历paying状态？

### ISSUE THREAD

**Issue by bruce452** [changmingxie/tcc-transaction#243]
PaymentServiceImpl中的makePayment方法对order对象的状态和版本进行了更新，同时运用orderRepository.updateOrder(order)，将数据库中的记录进行更新，但是在debug的过程当中，发现执行完这条语句之后，数据库中的记录并没有更改。

**Comment by woshiliujie** [comment]
整个事务还没提交吧。
我买第二个东西，资金账户钱不够，发现order的状态还是DRAFT，按道理执行cancel后应该是PAY_FAILED状态
