### ISSUE TITLE
dubbo 回滚是有问题的

### ISSUE THREAD

**Issue by dongdongqin** [changmingxie/tcc-transaction#244]
场景如下;
 从dubbo 的 sample中，下面两句。我在最后抛出个异常，这样的异常会导致回滚的问题。
      
        String result = capitalTradeOrderService.record(buildCapitalTradeOrderDto(order));
        String result2 = redPacketTradeOrderService.record(buildRedPacketTradeOrderDto(order));
       throw new RuntimeException("");

     第一: capitalTradeOrderService.record 和 redPacketTradeOrderService.record 都不会回滚的，因为已经执行完了， try 和 confirm 都做完了。dubbo 远程调用，provider方，会有自己的逻辑判断。
     第二: 本地这个应用会执行  try,和 cancel, 

   其实这样，已经导致了数据不一致的问题了。
不知道我理解的对不对，我感觉是没有问题的。请帮忙解决这样的问题，谢谢！
本质的问题是，global transaction 没有办法控制 所有微服务的回滚

**Comment by dongdongqin** [comment]
另外一个问题是接着上面所描述的问题:
      如何再confirm 阶段 ，其中有个confirm 发生了错误，比如 result， 当result2 发生了问题，怎么办?
   String result = capitalTradeOrderService.record(buildCapitalTradeOrderDto(order));
    String result2 = redPacketTradeOrderService.record(buildRedPacketTradeOrderDto(order));

此时是不是都会调用cancel 回滚呢?

**Comment by MrYangcg** [comment]
> 场景如下;
> 从dubbo 的 sample中，下面两句。我在最后抛出个异常，这样的异常会导致回滚的问题。
> 
> ```
>     String result = capitalTradeOrderService.record(buildCapitalTradeOrderDto(order));
>     String result2 = redPacketTradeOrderService.record(buildRedPacketTradeOrderDto(order));
>    throw new RuntimeException("");
> 
>  第一: capitalTradeOrderService.record 和 redPacketTradeOrderService.record 都不会回滚的，因为已经执行完了， try 和 confirm 都做完了。dubbo 远程调用，provider方，会有自己的逻辑判断。
>  第二: 本地这个应用会执行  try,和 cancel, 
> ```
> 
> 其实这样，已经导致了数据不一致的问题了。
> 不知道我理解的对不对，我感觉是没有问题的。请帮忙解决这样的问题，谢谢！
> 本质的问题是，global transaction 没有办法控制 所有微服务的回滚

为什么不会回滚呢？你有没有本地试过呢？不会回滚的话那它就没实现分布式事务的基本功能呀
