### ISSUE TITLE
http sample示例 findByShopId取数据的时候报错了，都能调通吗？

### ISSUE THREAD

**Issue by wuhaiyou** [changmingxie/tcc-transaction#245]
http sample示例 findByShopId取数据的时候报错了，都能调通吗？
error may exist in URL [jar:file:/C:/apache-tomcat-9.0.16/webapps/one/WEB-INF/lib/tcc-transaction-sample-order-1.2.4.24.jar!/config/sqlmap/main/sample-product.xml]
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)

**Comment by newpant** [comment]
看错误，没连接上数据库啊，DB配置信息没问题吗？
