### ISSUE TITLE
极端情况下timeout，引发数据不一致问题

### ISSUE THREAD

**Issue by liyiyong1211** [changmingxie/tcc-transaction#249]
看了源码，想了很久，如果try执行超时，由补偿器执行cancel时，try中的业务数据还未提交(执行慢)，补偿是会成功的，此时主事物日志会删除     如果后面try业务数据提交，会导致这部分预占资源无法回滚    请问这种理解对不对？如果对，如何避免try执行慢，导致这种情况的发生，如果执行增大补偿时间，无法完全避免    望解答，谢谢

**Comment by liyiyong1211** [comment]
@changmingxie

**Comment by liyiyong1211** [comment]
特别是嵌套调用，会产生很多不可控的因素

**Comment by liyiyong1211** [comment]
特别是嵌套调用，会产生很多不可控的因素

**Comment by changmingxie** [comment]
@liyiyong1211 可以设置delayCancelExcepiton，当遇到delayCancelException时将不会立即执行cancel，而是在其后恢复job再处理。默认把timeout exception加了，可以配置其他exception。

**Comment by liyiyong1211** [comment]
是加入了delayCancelExcepiton中，由消息job进行补偿，但是由于网络或数据库执行慢，trying执行时间可能不可控，导致trying事务提交在cancel执行完成之后的极端情况    按现有源码来看，将出现tcc日志都会被cancel删除，trying占用的资源将无法释放

**Comment by changmingxie** [comment]
@liyiyong1211 恢复周期内(默认2分钟)try过程一定结束了的，这个是需要约定保证的，比如try阶段数据库操作，超时时间得设置小于恢复周期；可以根据业务情况来设置恢复周期。
