### ISSUE TITLE
Confirm异常问题

### ISSUE THREAD

**Issue by terry8210** [changmingxie/tcc-transaction#25]
如果在Confirm中抛出异常，异常会抛给服务调用方吗？
如果Confirm抛出异常，是否所有事务步骤中的都会调用cancel接口？

**Comment by streammemoryli** [comment]
confirm出现的异常，除了NoExistedTransactionException外都会向外抛出
confirm出现异常，不会调用cancel
try—cancel
try—confirm
只有这两条操作路径，没有其它

**Comment by outman1234** [comment]
万一由于网络异常 导致confirm异常了呢？？该怎么办啊

**Comment by lechiw** [comment]
@outman1234  confirm异常，tcc会重试maxRetryCount次，maxRetryCount次后仍然无法正常执行，可进行人工干预进行处理

**Comment by 15313335298** [comment]
我使用的http-sample模块的 并不会定时发起重试confirm
