### ISSUE TITLE
getUniqueIdentity() 返回null导致NPE

### ISSUE THREAD

**Issue by quaider** [changmingxie/tcc-transaction#254]
`CompensableMethodContext.getUniqueIdentity()`方法返回null，导致 TransactionXid实例化时报错NPE，
最近是在1.2.x上做了什么改动吗？
@changmingxie

**Comment by ahexian** [comment]
同问

**Comment by yeweijun4703** [comment]
https://github.com/changmingxie/tcc-transaction/issues/262#issuecomment-498178706

**Comment by changmingxie** [comment]
@quaider 谢谢，是个bug，已在1.2.7 fix.

**Comment by jinyue233** [comment]
同问
