### ISSUE TITLE
按照1.2.x的使用手册, 1.2.6版本无法使用

### ISSUE THREAD

**Issue by wulongmin** [changmingxie/tcc-transaction#262]
1.sample运行起来业务执行有问题. 报错后查看源码是方法参数缺少 @UniqueIdentity注解

2.添加注解后, 运行业务, 主业务A调用 服务B. 
> 成功的场景, 业务A会调用try和confirm方法. 服务B只会调用 try方法.

3.第一次运行时, 调用方法会有执行, 执行一次后, 再次调用同一个方法, 返回值null, 并且不走主业务里的代码.
> 每次调用传入的 UniqueIdentity 的参数值是唯一的

**Comment by yeweijun4703** [comment]
Object org.mengyun.tcctransaction.interceptor.CompensableMethodContext.getUniqueIdentity()

最终返回值改成 return UUID.randomUUID(); 试试

**Comment by wulongmin** [comment]
问题解决.
1.切换master-1.2.x分支到2018-7月份左右的代码. 版本是1.2.4.xx

2.主服务-事务发起方的注解, 不能写transactionContextEditor = DubboTransactionContextEditor.class, 这个值保持默认即可

3.springboot的项目, 不能用Dubbo-starter的@Reference注解来进行注入. 一定要使用xml的方式去配置引用服务.否则分布式事务不生效
