### ISSUE TITLE
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection;

### ISSUE THREAD

**Issue by astorage** [changmingxie/tcc-transaction#266]
这个错误是因为，数据库jar包版本太旧了。需要更新一下数据库jar的版本

![image](https://user-images.githubusercontent.com/7079492/60332421-5aa8d100-99c9-11e9-9000-0dfdfb12e118.png)

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
