### ISSUE TITLE
double demo中为什么在消费端通过反射获取的方法@Compensable注解confirmMethod、cancelmethod都是record？

### ISSUE THREAD

**Issue by astorage** [changmingxie/tcc-transaction#268]
![image](https://user-images.githubusercontent.com/7079492/60796973-05c34280-a1a1-11e9-9a34-7a30b0882d36.png)

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频

**Comment by bigcoder84** [comment]
因为是通过Dubbo隐私传参，传递的参数中包含事务状态，下游服务（Dubbo）会由AOP切面处理事务状态逻辑（org.mengyun.tcctransaction.interceptor.CompensableTransactionInterceptor#providerMethodProceed）根据不同的事务状态会去调用不同的方法
