### ISSUE TITLE
注解方法工具里的这段代码，第一个method的获取与第二个有什么区别

### ISSUE THREAD

**Issue by renxinlin** [changmingxie/tcc-transaction#275]
public static Method getCompensableMethod(ProceedingJoinPoint pjp) {
        Method method = ((MethodSignature) (pjp.getSignature())).getMethod();

        if (method.getAnnotation(Compensable.class) == null) {
            try {
                method = pjp.getTarget().getClass().getMethod(method.getName(), method.getParameterTypes());
            } catch (NoSuchMethodException e) {
                return null;
            }
        }
        return method;
    }

**Comment by zhuyou1234** [comment]
> ```
> public static Method getCompensableMethod(ProceedingJoinPoint pjp) {
>     Method method = ((MethodSignature) (pjp.getSignature())).getMethod();
> 
>     if (method.getAnnotation(Compensable.class) == null) {
>         try {
>             method = pjp.getTarget().getClass().getMethod(method.getName(), method.getParameterTypes());
>         } catch (NoSuchMethodException e) {
>             return null;
>         }
>     }
>     return method;
> }
> ```

see https://stackoverflow.com/questions/5714411/getting-the-java-lang-reflect-method-from-a-proceedingjoinpoint
You should be careful because Method method = signature.getMethod() will return the method of the interface, you should add this to be sure to get the method of the implementation class:

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
