### ISSUE TITLE
Confirm 阶段失败，重复提交的问题

### ISSUE THREAD

**Issue by lindengCm** [changmingxie/tcc-transaction#276]
一个方法里面两个Service，A service和B service ，现在A 和 B 都try成功了，A confirm成功了，B confirm 失败。那么后面就会重复 A confirm ，B confirm 操作，如果B 好了，那么A 不是执行了很多次 confirm么？这个怎么避免？

**Comment by Mprotecter** [comment]
这里就是作者说的要实现幂等的地方，有思路了吗请问

**Comment by ZhangMouJiang** [comment]
补偿型的方案，你就必须要保证接口的幂等性。解决幂等性的方案有多种，可度娘、狗狗

**Comment by bioxuxuan** [comment]
使用状态机结合事务，解决幂等性问题

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
