### ISSUE TITLE
插入tcc_transaction_ord的数据过一会就回滚了

### ISSUE THREAD

**Issue by BestCoderzzx** [changmingxie/tcc-transaction#279]
过一段时间过 插入tcc_transaction_ord表的数据过一会就回滚了
![image](https://user-images.githubusercontent.com/46521410/63206397-2fe41a80-c0e6-11e9-912e-9e255ecc3e6f.png)

**Comment by xvxingan** [comment]
是不是使用了Druid连接池呢。我使用Druid连接池时有相同的问题。这是我提交的issue：
https://github.com/changmingxie/tcc-transaction/issues/282#issue-489668913
