### ISSUE TITLE
no such extension com.alibaba.dubbo.rpc.proxyFactory by name tccJavassist

### ISSUE THREAD

**Issue by zsz0817** [changmingxie/tcc-transaction#284]
在dubbo配置<dubbo:provider proxy="tccJavassist"/>之后，其他有调用到该服务的dubbo服务启动报错，no such extension com.alibaba.dubbo.rpc.proxyFactory by name tccJavassist

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
