### ISSUE TITLE
请教下调用逻辑

### ISSUE THREAD

**Issue by wpf5788** [changmingxie/tcc-transaction#29]
请教下， order中调用 capitalTradeOrderServiceImpl.record后，如果record try时失败，order怎么会知道record和try失败了呢   看了源码不太理解这个是怎么处理的，进入这些方法的时候aop处理了transcation表 这个倒是清楚的

**Comment by wpf5788** [comment]
大虾  在不在  或者其它人也行

**Comment by wpf5788** [comment]
理解了    如果远程调用失败会报错，报错由order捕获到，触发所有回滚

**Comment by liuyb02** [comment]
调用方做协调者，成功时触发所有参与者提交，失败时触发回滚

**Comment by kwengelie** [comment]
@liuyb02 看源代码没看出来调研方是如何协调的
