### ISSUE TITLE
通过RestTemplate调用的服务怎么保持事务一致啊？

### ISSUE THREAD

**Issue by 2550462328** [changmingxie/tcc-transaction#290]
springData那种服务调用方式（直接通过RestTemplate）的话，怎么传递TransactionContext，现在在tcc服务方的TransactionContext参数为空，主服务的事务和调用服务的事务不在一起，现有的框架能支持这种吗？
![image](https://user-images.githubusercontent.com/30400766/69217668-20271700-0baa-11ea-8afc-aa56f118dc2f.png)

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
