### ISSUE TITLE
关于demo项目之间依赖过度复杂问题

### ISSUE THREAD

**Issue by SxMaster** [changmingxie/tcc-transaction#295]
个人觉得作者构建的demo, maven项目依赖过于复杂，对新手非常不友好。demo的主要目的是通过简单的例子让然快速入手，有一个直观的理解。还有在order服务中try阶段手动抛出异常，导致分布式事务一致性失败。

**Comment by changmingxie** [comment]
可参考1.6.3版的sample, 以及快速入门 指南。
