### ISSUE TITLE
tcc-spring 改成spring-boot自动注入模式，并介绍支持spring-cloud，源码详解

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [changmingxie/tcc-transaction#296]
[tcc-transaction-spring.zip](https://github.com/changmingxie/tcc-transaction/files/4154455/tcc-transaction-spring.zip)

**Comment by Daiqiangdeveloper** [comment]
具体使用方，比如：TccConfig.java  只需要配置TransactionRepository以及重试策略RecoverConfig

import org.mengyun.tcctransaction.TransactionRepository;
import org.mengyun.tcctransaction.recover.RecoverConfig;
import org.mengyun.tcctransaction.serializer.KryoPoolSerializer;
import org.mengyun.tcctransaction.serializer.ObjectSerializer;
import org.mengyun.tcctransaction.spring.recover.DefaultRecoverConfig;
import org.mengyun.tcctransaction.spring.repository.SpringJdbcTransactionRepository;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;

@Configuration
public class TccConfig {
    


    @Bean
    public TransactionRepository transactionRepository(@Qualifier("transactionDataSource")DataSource dataSource, ObjectSerializer objectSerializer) {
        SpringJdbcTransactionRepository springJdbcTransactionRepository = new SpringJdbcTransactionRepository();
        springJdbcTransactionRepository.setDataSource(dataSource);
        springJdbcTransactionRepository.setSerializer(objectSerializer);
        springJdbcTransactionRepository.setTbSuffix("__MEMBER");
        springJdbcTransactionRepository.setDomain("MEMBER");
        return springJdbcTransactionRepository;
    }

    @Bean
    public ObjectSerializer objectSerializer() {
        return new KryoPoolSerializer();
    }

    @Bean
    public RecoverConfig recoverConfig() {
        DefaultRecoverConfig recoverConfig = new DefaultRecoverConfig();
        recoverConfig.setMaxRetryCount(30);
        recoverConfig.setCronExpression("0/5 * * * * ?");
        recoverConfig.setRecoverDuration(5);
        return recoverConfig;
    }



}

**Comment by Daiqiangdeveloper** [comment]
tcc-transaction使用:https://blog.csdn.net/sinat_33543436/article/details/104180637
源码详解：https://blog.csdn.net/sinat_33543436/article/details/104182790

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
