### ISSUE TITLE
不支持防悬挂控制？

### ISSUE THREAD

**Issue by Rocky-Hu** [changmingxie/tcc-transaction#299]
看了这篇文章：

[https://www.sofastack.tech/blog/sofa-meetup-3-seata-retrospect/](https://www.sofastack.tech/blog/sofa-meetup-3-seata-retrospect/)

里面有个防悬挂的控制。看了代码，貌似是不支持的。

**Comment by Rocky-Hu** [comment]
测试了一下，设置超时异常，可能会解决cancel比try先执行，try最终执行的问题。

但只是可能，如果在超时异常处理的时间范围内，try执行完成了，那么定时任务处理，事务参与方收到rollback通知，可以取消延期执行的try。

但是，如果超过超时异常处理的时间范围之后，try再执行完成，那么因为事务管理器已经发送了rollback通知，事务发起方的事务已经删除了，那么就不会再次发送rollback来取消事务参与方状态为TRYING的日志。

通过在org.mengyun.tcctransaction.interceptor.CompensableTransactionInterceptor#providerMethodProceed的TRYING状态处理处打断点，可以模拟这个问题。

**Comment by changmingxie** [comment]
参考1.6.x, 支持防悬挂

https://github.com/changmingxie/tcc-transaction/issues/328
