### ISSUE TITLE
tccdemo中TCC的根confirm没有触发。

### ISSUE THREAD

**Issue by wuherong** [changmingxie/tcc-transaction#3]
tcc-transaction-dubbo-sample 实例  order ,cap,red中下订单时，ord try方法调用cap,red的try方法后，order的confirm没有调用，cap,red的confirm方法调用，但是订单的状态还是PAYING状态，confirm方法会异常？这应该不可能呀，这个只是改order的状态。后台也没有出现异常栈。那这样的话是不是就没有起到tcc的事务控制功能。
makePayment try

capital try record called
capital confirm record called

red packet try record called
red packet confirm record called

**Comment by changmingxie** [comment]
@wuherong 
你好，查看了下sample示例，确实存在你说的问题，排查问题 发现spring里有个配置没有配置好 导致order项目中的@Compensable注解的方法没有被拦截。解决办法是 将 <aop:aspectj-autoproxy proxy-target-class="true"/> 加在appcontext-web-servlet.xml中，另外示例中Order 和 OrderLine需要实现Serializable接口，因为tcc 方法的入参需要能序列化，不然也会报错。更新后的sample可以运行了。测试输出结果及顺序应该如下：
 order项目输出：
    t1: order try make payment called
    t4:order confirm make payment called
capital项目：
    t2:capital try record called
    t5:capital confirm record called
redpacket项目：
    t3:red packet try record called
    t6:red packet confirm record called
