### ISSUE TITLE
分布式服务调用链，中间节点异常，如何对全部节点进行回滚服务进行事务补偿

### ISSUE THREAD

**Issue by jansun2016** [changmingxie/tcc-transaction#30]
比如现在有 分布式服务A,B,C,D,E,F。存在着调用链 A->B,B->C,C->D,D->E,E->F，假如D->E出现超时异常或是业务异常时, 分布式事务框架如何实现支持执行A->B,B->C,C->D 的回滚服务进行事务补偿，请问能否提供相应的demo程序？

**Comment by changmingxie** [comment]
@jansun2016 如果D->E在Try阶段异常了，会触发A->B,B->C,C->D,D->E的Cancel方法；目前有一个unit test，可以看看tcc-transaction-unit-test项目下面这个测试方法：
TransferServiceTest.testTransferWithMultipleTier
