### ISSUE TITLE
事务恢复job

### ISSUE THREAD

**Issue by zanjun9527** [changmingxie/tcc-transaction#303]
============代码如下=============
来源：org.mengyun.tcctransaction.recover.TransactionRecovery#recoverErrorTransactions

 if (transaction.getTransactionType().equals(TransactionType.BRANCH)
                    && (transaction.getCreateTime().getTime() +
                    transactionConfigurator.getRecoverConfig().getMaxRetryCount() *
                            transactionConfigurator.getRecoverConfig().getRecoverDuration() * 1000
                    > System.currentTimeMillis())) {
                continue;
            }
============代码如上=============

这里的设计啥意思啊，是分支事务的恢复只能等最大恢复时间之后才能触发?
是不是这里的“>”反了？  有大佬看这部分的吗

**Comment by ZhangMouJiang** [comment]
你提的是一个问题，还有个问题就是：tcc通过事务消息日志状态 try、cancel、confirm，来进行重试。目前只对两种 cancel、confirm的两种状态超过指定时间进行重试。 难道就不可能存在try状态的日志吗？ 当自身系统宕机的时候，还没来得及将事务更新为cancel，那么事务消息不就一直停留在了try吗？之前调用其他系统的资源不就一直被锁住了吗？

**Comment by zanjun9527** [comment]
你再dubbo的demo这org.mengyun.tcctransaction.sample.dubbo.order.service.PaymentServiceImpl.makePayment()
 orderRepository.updateOrder(order);之后打个断点，然后关掉工程测试下就知道有没有try状态事务啦？run一下看看。不过这里try一般预留资源，在org.mengyun.tcctransaction.interceptor.CompensableTransactionInterceptor#rootMethodProceed
中已经捕获业务异常了，你的断电可能性可以自己run一下看看

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
