### ISSUE TITLE
在try里面获得的数据，如何让confirm使用？

### ISSUE THREAD

**Issue by xiaolshi** [changmingxie/tcc-transaction#306]

**Comment by RabbitsInTheGrass** [comment]
我尝试的过程中发现。你可以把你try里面获得的数据，在方法的入参里做个特殊的属性去接收。这样confirm方法里能拿到这个修改后的属性。

**Comment by changmingxie** [comment]
由于confirm可能会异步、延迟执行，通过简单的方法传递并不可靠，可以通过其他方式在confirm 重新获取。
