### ISSUE TITLE
实现动态全局事务管理开关

### ISSUE THREAD

**Issue by aerofish** [changmingxie/tcc-transaction#307]
您好，我正打算集成tcc-transaction，在学习过程中，我发现我有需求需要动态的开关全局事务管理。意思是我已有的业务代码需要区分两种情况，一些处理流程需要开启全局事务管理，一些处理流程只要本地事务就可以了。另外我不想实现两个不同的分支，代码完全一样，只有一个@Compensable的区别。所以是不是可以考虑在注解中加一两个额外的参数去实现根据定制的参数去开关是否执行全局事务管理。
比如增加一个参数bypass，如果在调用方式传bypass，那么拦截器就不会做任何处理。

或者其实已经有现成的功能了我没找到？

**Comment by changmingxie** [comment]
目前暂无该功能
