### ISSUE TITLE
测试出现的2个问题

### ISSUE THREAD

**Issue by a402942988** [changmingxie/tcc-transaction#309]
我使用的是springboot+dubbo
测试demo-dubbo出现2个问题：
1. 如果使用dubbo注解方式
![111](https://user-images.githubusercontent.com/22361202/87134729-a7590480-c2cb-11ea-8a83-53c06cfff492.PNG)
当在蓝色框中的代码抛出异常时，只有order的服务会调用rollback，其他远程服务会调用confirm方法。
2. 使用原生demo-dubbo测试时，也就是xml配置的dubbo，如果把check=false，然后先启动消费者，在启动提供者，在蓝色框中报错，也会出现上面说的问题。
===================================================
个人测试没有问题的流程：基于xml配置，先启动提供者，再启动消费者。
个人觉得框架还是很好用，感谢作者

**Comment by changmingxie** [comment]
目前在1.6.x上没有发现您说的情况，可以用1.6.x再验证下
