### ISSUE TITLE
请问本项目对服务调用幂等性有要求吗?

### ISSUE THREAD

**Issue by SandyJiang** [changmingxie/tcc-transaction#31]
非幂等的想保证不被重复调用,该怎么做.

**Comment by changmingxie** [comment]
@SandyJiang  服务被调用后，会更新日志记录；如果日志更新成功，则该服务不会被重复调用，如果写日志不成功，则 会重试，重试时 会重复调用该服务并再次更新日志记录。比如：A->B，当调用B的Try方法异常了，则框架会调用A的Cancel方法和B的Cancel方法（Confirm方法异常与之类似，只是会尝试调用Confirm方法）。考虑调用B的Cancel方法情况，首先框架会写事务日志，表示B参与的事务进入CANCEL状态，接着调用B的Cancel方法，如果Cancel方法没有异常，则会更新事务日志（删除B对应的日志记录）表示B已成功Cancel了，即使后续其他事务参与者有异常造成整个事务依旧没有Cancel完成，框架重试机制会继续尝试Cancel整个事务，这时也不会再调用B的Cancel方法了。如果调用B的Cancel方法异常了，或是调用B的Cancel方法正常，但是更新B的事务日志（删除B对应的日志记录）异常了，则整个事务为完成状态，框架重试机制会继续尝试Cancel整个事务，这时还会尝试调用B的Cancel方法，更新B的事务日志（删除B对应的日志记录），这种情况下B的Cancel方法会再次调用。

**Comment by uguesswhoami** [comment]
如果调用B的Cancel方法异常了，或是调用B的Cancel方法正常，但是更新B的事务日志（删除B对应的日志记录）异常了，则整个事务为未完成状态，框架重试机制会继续尝试Cancel整个事务，这时还会尝试调用B的Cancel方法，更新B的事务日志（删除B对应的日志记录），这种情况下B的Cancel方法会再次调用。
这边有个疑问：
那这样岂不是又没法保证Cancel的幂等了？Cancel还是会执行，应该将“更新B的事务日志”和“B的Cancel方法调用”放在一个事务里吧？

**Comment by changmingxie** [comment]
@uguesswhoami Cancel的幂等性由Cancel方法自己保证。

**Comment by uguesswhoami** [comment]
、恩？  上面回答里的“写事务日志”和“更新事务日志”不是保证cancle方法的幂等性的么？
