### ISSUE TITLE
tcc-transaction 1.2.12 api模块,TransactionXid 定制事务编号

### ISSUE THREAD

**Issue by LinMingHang** [changmingxie/tcc-transaction#311]
org.mengyun.tcctransaction.api
public class TransactionXid implements Xid, Serializable {
    private static byte[] CUSTOMIZED_TRANSACTION_ID = "UniqueIdentity".getBytes();
}

此处的全局事务ID 不唯一,直接写死,导致不同事务的全局事务ID不唯一. 不利于后面的扩展.

**Comment by changmingxie** [comment]
谢谢建议，xid由2部分组成，第2部分 是不一样的，不会不唯一。
