### ISSUE TITLE
tcc-http-sample 样例演示购买超链接 抛异常 java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by wangxg253632225** [changmingxie/tcc-transaction#316]
![image](https://user-images.githubusercontent.com/19992973/103604407-f2d32f00-4f4b-11eb-8dfc-33bbdacc14bc.png)
抛异常如下：
![image](https://user-images.githubusercontent.com/19992973/103604429-041c3b80-4f4c-11eb-9f09-dc4935742418.png)

数据库驱动配置：mysql-connector-java   版本 :8.0.16

**Comment by changmingxie** [comment]
查看provider方 是不是有报错
