### ISSUE TITLE
why TradeOrderServiceProxy.record  need  @Compensable ?

### ISSUE THREAD

**Issue by jiemar** [changmingxie/tcc-transaction#317]
why TradeOrderServiceProxy.record  need  @Compensable ? it's invoker PaymentServiceImpl.makePayment already has @Compensable
and why the confirmMethod and cancelMethod are all record?

![image](https://user-images.githubusercontent.com/1522163/106831114-4b702600-66ca-11eb-8b2b-09d3139bb86c.png)

**Comment by changmingxie** [comment]
参考1.6.x，可以无需添加
