### ISSUE TITLE
sample中dubbo方式数据库问题

### ISSUE THREAD

**Issue by 1037861070** [changmingxie/tcc-transaction#318]
1、1.2.x中在capital、redpacket、order中只有tcc数据库，没有各自系统的数据库jdbc连接，不需要配置各自的库？
2、没有实现幂等，在redpacket和capital系统中的confirmRecord方法中，变更状态后，需要将扣除金额的字段置0，然后余额不做变化，此capital账户和redpacket账户系统中没有变更金额字段，直接与cancel方法恢复余额了，没有做到幂等吧，真实场景应该是在表中新加一个冻结金额的字段

**Comment by changmingxie** [comment]
confirm cancel 需要实现密等
