### ISSUE TITLE
新版本独立事务库问题

### ISSUE THREAD

**Issue by streammemoryli** [changmingxie/tcc-transaction#32]
不建议采用独立事务库
1：大压力下，独立事务库性能是否会成为瓶颈
2：独立事务库，会给系统带来额外的不确定性。本身它不属于业务库，但它出现问题，会导致整个系统无法运行

**Comment by changmingxie** [comment]
@streammemoryli 新版依旧可以将日志表放在各自项目里，与旧版是完全兼容的；
新版主要是增加tcc-transaction-server,方便异常日志查看；

**Comment by streammemoryli** [comment]
如果使用tcc-transaction-server，是否需要事务存储在一个库中？

**Comment by changmingxie** [comment]
@streammemoryli 可以不需要，可以配置成链接到各自项目的日志表中。
