### ISSUE TITLE
使用接口调用时无法触发AOP创建TCC事务

### ISSUE THREAD

**Issue by liuyb02** [changmingxie/tcc-transaction#33]
建议修改spring配置，增加对子类和接口方式调用时tcc的支持
<aop:aspectj-autoproxy proxy-target-class="true" />

**Comment by changmingxie** [comment]
@liuyb02 能举例说明下 期望的调用方式么？

**Comment by liuyb02** [comment]
1、目前我的应用中所有都是通过接口调用，包括ROOT也是通过接口反射调用。我发现如果不加proxy-target-class就不能被compensable的aspect捕获到。我改后可以了。
2、另外confirm和cancel方法是不是也应该加compensable注解？我看你代码里provider的处理里有，如果不加没法propagationexist。
3、threadlocal存的transaction如果有嵌套调用或者同一线程两次调用时就会造成覆盖，我在自己代码里改成用stack，在操作进入和退出时通过入栈出栈的方法保存前一个transaction。
@changmingxie

**Comment by lovelivestyle1102** [comment]
@liuyb02 请问的嵌套事务是怎么做的。我现在嵌套出现很多异常，页出现部分业务调用俩次一些confirm又不调用的情况。
