### ISSUE TITLE
目前有多少公司使用了

### ISSUE THREAD

**Issue by chenlong12** [changmingxie/tcc-transaction#37]
如题，大家统计下呗

**Comment by wukonggg** [comment]
@changmingxie 请问作者，有没有生产环境的应用案例？能否给具体说明一下？

**Comment by changmingxie** [comment]
@wukonggg 没有统计，目前我所在公司在用，主要是用RedisTransactionRepository做日志存储，写日志性能影响在2ms以下。

**Comment by wukonggg** [comment]
@changmingxie 谢谢你的答复~
