### ISSUE TITLE
实现原理没看懂，谁能解答下

### ISSUE THREAD

**Issue by chenlong12** [changmingxie/tcc-transaction#40]
1.为什么执行
  String result = capitalTradeOrderService.record(null, buildCapitalTradeOrderDto(order));
是先被TccTransactionContextAspect拦截的，他的order值比较大，不应该是TccCompensableAspect先拦截嘛？

2.异常的时候具体是哪段代码会去调用cancel的方法

**Comment by pktczwd** [comment]
1.TccCompensableAspect先拦截. order的值越大,优先级越低.TccCompensableAspect的order值是Integer.MIN_VALUE,而TccTransactionContextAspect的order值为Integer.MIN_VALUE+1.所以TccCompensableAspect先拦截.

2.CompensableTransactionInterceptor.rootMethodProceed(), 在trying阶段遇到错误之后,将会由TransactionManager发起事务的回滚.
