### ISSUE TITLE
tcc-transaction-server找不到下载地址

### ISSUE THREAD

**Issue by dayu521** [changmingxie/tcc-transaction#413]
部署文档中,[server单机部署](https://changmingxie.github.io/zh-cn/docs/ops/server/deploy-alone.html)中,需要下载tcc-transaction-server

在给出的链接中https://github.com/changmingxie/tcc-transaction/releases ,没有找到下载地址,只看到源码下载地址,

不好意思,实在找不到了

**Comment by nervose** [comment]
很抱歉，2.0.1之前的版本确实没有提供server/dashboard的下载地址，需要通过下载源码打包获取。
2.0.2及后续版本可通过Release页获取

**Comment by nervose** [comment]
很抱歉，2.0.1之前的版本确实没有提供server/dashboard的下载地址，需要通过下载源码打包获取。
2.0.2及后续版本可在Release页获取。
