### ISSUE TITLE
ResourceCoordinatorInterceptor代码疑问

### ISSUE THREAD

**Issue by huangcheng1977** [changmingxie/tcc-transaction#43]
如标题中的类，以下代码是什么意思，consumer和provider是什么
   MethodType methodType = CompensableMethodUtils.calculateMethodType(transactionContext, compensable != null ? true : false);

            switch (methodType) {
                case ROOT:
                    generateAndEnlistRootParticipant(pjp);
                    break;
                case CONSUMER:
                    generateAndEnlistConsumerParticipant(pjp);
                    break;
                case PROVIDER:
                    generateAndEnlistProviderParticipant(pjp);
                    break;
            }

**Comment by AllenRay** [comment]
consumer 就是rpc的消费端，provider就是rpc的服务提供端。
