### ISSUE TITLE
create_db_ord.sql

### ISSUE THREAD

**Issue by weldon01** [changmingxie/tcc-transaction#46]
create_db_ord.sql中的INSERT INTO `ORD_SHOP` (`SHOP_ID`,`OWNER_USER_ID`) VALUES (1,10000);其中的10000要改成1000才对，要不然，跟账户中的用户ID对不上。

**Comment by changmingxie** [comment]
@weldon01 已改。

**Comment by lisongqiu168** [comment]
create_db.sql在哪里
