### ISSUE TITLE
发现了几个问题 请教一下

### ISSUE THREAD

**Issue by xuxiaolu** [changmingxie/tcc-transaction#48]
1. dubbo使用注解的方式无效 ResourceCoordinatorInterceptor 的interceptTransactionContextMethod这个方法，methodType永远为root
2.http方式请求的时候也是一样的

**Comment by changmingxie** [comment]
@xuxiaolu 估计是配置问题，可以参考
https://github.com/changmingxie/tcc-transaction/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
进行配置。

**Comment by xuxiaolu** [comment]
我只是把order那个服务CapitalTradeOrderService 的注解改为@Refenerce 这样的话 走不到generateAndEnlistConsumerParticipant里面了

**Comment by xuxiaolu** [comment]
http请求别的服务一样是走不到generateAndEnlistConsumerParticipant
