### ISSUE TITLE
急！基于soa的事务管理疑问

### ISSUE THREAD

**Issue by buguniao** [changmingxie/tcc-transaction#50]
按照您的代码实现来看，请问如何解决下面这个场景的问题：
1、一个事务下有两个参与者service1、service2，service1 转账100元给service2
2、try 阶段，service1 - 100 ，成功。service2 + 100 ，失败。
3、cancel阶段，service1、service2都执行cancel方法，service1 + 100，service2 - 100
4、 结果就是 service1、 service2  回滚到未转账之前的状态，一切看起来很完美！

但是， service2虽然失败了，但一定需要cancel吗？

比如 service2中的方法是这样写的：

    public void transferTo(TransactionContext transactionContext, long accountId, int amount) {
           throw new Exception("我故意抛异常"); // 方法立即抛异常
           accoutDao.addBalanceAmount(accountId,amount);// service2 加了100元 
    }

然后在cancel 阶段 ,service1+100、service2-100
但是service2之前根本没有加过100
结果就是service1 金额正确，service2 金额被无缘无故的减了100
----------------------
问题就在于：基于服务而不是基于数据库资源的事务管理，在不能判断抛异常是由于其他业务逻辑造成还是因为数据库操作失败造成的情况下就进行回滚是存在问题的

**Comment by changmingxie** [comment]
@buguniao 根据你的例子，事务应该是按照下面流程：
1. try ：service1－100，
2. confirm: 如果service2没有加100，则service2+100.
3. cancel: 如果service1减了100，则service1+100.

**Comment by liuguozhuchina** [comment]
其实你的目的就是要解决分布式事务问题，分布式事务你可以通过三种方式解决，网上资料很多，我的理解rpc 框架不应该做这样的事情。

**Comment by buguniao** [comment]
感谢回信，不过还有点疑问：
1、我的理解是在try阶段应该尽可能把该做的事情都做了， service1 - 100  && service2 +100
confirm和cancel阶段只是针对try阶段做确认或者回滚，而不是跟你上边说的，try阶段只是做  service1 - 100

**Comment by kixiong** [comment]
service2必须判断是否加过100，加过才减一百，否则不动。


发自网易邮箱大师
在2016年12月10日 11:10，buguniao 写道:

按照您的代码实现来看，请问如何解决下面这个场景的问题：
1、一个事务下有两个参与者service1、service2，service1 转账100元给service2
2、try 阶段service1减去100元，成功，service2失败
3、开始cancel阶段，将service1、service2都执行cancel方法，service1加100，service2减100

问题：
service2失败，但一定需要cancel吗？
比如 service2中的方法是这样写的：

public void transferTo(TransactionContext transactionContext, long accountId, int amount) {
       throw new Exception("我故意抛异常"); // 方法立即抛异常
       accoutDao.addBalanceAmount(accountId,amount);// service2 加了100元 
}


然后在cancel 阶段 ,service1+100、service2-100
但是service2之前根本没有加过100
结果就是service1 金额正确，service2 金额被无缘无故的减了100

**Comment by alexqdjay** [comment]
我想问下，service1的本地事务是什么时候提交的？
