### ISSUE TITLE
多线程设计的疑问

### ISSUE THREAD

**Issue by buguniao** [changmingxie/tcc-transaction#51]
如果下面这样简化，请帮看下是否存在问题？
首先，不在使用多线程，都在主线程中进行。
然后，root事务开始就在threadlocal中设置事务对象，后续所有事务参与者是通过查看threadlocal中是否存在事务，如果存在事务则自动作为分支事务参与其中

**Comment by buguniao** [comment]
如果下面这样简化，请帮看下是否存在问题？
首先，不在使用多线程，都在主线程中进行。
然后，root事务开始就在threadlocal中设置事务对象，后续所有事务参与者是通过查看threadlocal中是否存在事务，如果存在事务则自动作为分支事务参与其中

**Comment by changmingxie** [comment]
@buguniao 您是看tcc-transaction-unit-test这个项目中使用了多个线程产生的疑惑么？ 通常root事务和分支事务是在不同jvm进程的，unit test仅仅是用不同的线程来模拟事务在不同的进程程中的。
