### ISSUE TITLE
方法类型和分支事务的疑问

### ISSUE THREAD

**Issue by buguniao** [changmingxie/tcc-transaction#52]
1、看了下代码，您把方法分为ROOT、CONSUMER、PROVIDER、NORMAL 几种类型
root 主要是做充当事务协调者的角色。
consumer 作为provider中转，提前设置事务上下文，以方便分支事务做关联
provider 其实和root差不多，只是把root的上下文关联过来
normal 不做特殊处理
这几个类型的区分主要是靠1、是否存在@Compensable注解2、是否有TransactionContext等来判断，我个人觉得这会对业务逻辑有侵入性，能否考虑仅用注解来区分。
 
2、CONSUMER 类型方法的主要作用是建立起 根事务 和 分支事务的关联关系。这样设计我觉得主要是因为你的分支事务是在另外的线程中做的，通过consumer 方法作为中转，在进入到第二个线程之前在切面里设置了上下文信息，从而在第二个线程中可以关联到之前的事务，不知上述的理解是否有问题？

**Comment by changmingxie** [comment]
@buguniao 
1. TransactionContext 主要是作用是用来传输事务信息给远程服务。
2. 分支事务通常是不同的应用服务提供的，与根事务 是在不同的进程中，consumer主要是将事务信息传给远程服务。

**Comment by kixiong** [comment]
@changmingxie 
1. 我也是一直很纠结这个TransactionContext对业务系统的侵入，导致现有系统要使用这个TCC就需要修改。
2. 可以将TransactionContext这个使用dubbo的RpcContext这个类去隐式传参的

**Comment by changmingxie** [comment]
@kixiong 本是希望tcc-transaction不依赖底层具体rpc框架。关于使用dubbo的RpcContext隐式传参，在使用dubbo作为rpc框架时是个不错的做法，可以单独一个子项目考虑针对dubbo做些改进。
