### ISSUE TITLE
TCC事务同时调用后端多个服务，其中一个失败，其他成功的怎么知道恢复

### ISSUE THREAD

**Issue by goodluckwgw** [changmingxie/tcc-transaction#56]
TCC事务同时调用后端多个服务，其中一个失败，其他成功的怎么知道恢复

**Comment by pktczwd** [comment]
调用方将作为事务的协调者,当调用的远程服务有失败时,将主动调用所有远程服务的取消方法.

**Comment by goodluckwgw** [comment]
哥们，restful能应用吗

**Comment by pktczwd** [comment]
[restful示例](https://github.com/pktczwd/tcc-transaction)

**Comment by goodluckwgw** [comment]
thanks
