### ISSUE TITLE
用这个的人建议看清楚原理

### ISSUE THREAD

**Issue by jishaocong** [changmingxie/tcc-transaction#57]
这种错误回滚模式很容易理解，但是这种模式有很多个节点有可能出现服务宕机引起的问题，由于代码的simple案例很简单没看到有解决这些问题。tcc-transaction-service这个项目似乎是解决这些问题的策略，但是我觉得并不完美，依然有导致数据对账错误这种情况。另外错误回滚大家都认为是主动的，但是我觉得被动比较好，就说到这里。

**Comment by changmingxie** [comment]
@jishaocong 仔细看了你的问题，是说服务宕机会出现数据对账错误的问题，没太看明白 你说的什么情况？ 另外，你说的被动是分支事务能够自己主动恢复本地分支么？谢谢！
