### ISSUE TITLE
您好，provider和consumer是根据TransactionContext是否为null区分的？

### ISSUE THREAD

**Issue by BazingaLyn** [changmingxie/tcc-transaction#59]
我刚刚开始看您的源代码，我想问下，您这里的provider是分布式服务的中服务的提供者方吗，如果是，我看您的源码上是【transactionContext != null】来判定的，但是我看【capitalTradeOrderService.record(null, buildCapitalTradeOrderDto(order))】是传递null值的，那么服务提供者受到的TransactionContext就是null，这边我就不太理解了，应该是我理解错了，麻烦有空指导一下，provider端的TransactionContext是如何不是null的，唯一看赋值就是[ pjp.getArgs()[position] = new TransactionContext(xid, transaction.getStatus().getId());]这段代码了~

**Comment by changmingxie** [comment]
@BazingaLyn 是的。

**Comment by BazingaLyn** [comment]
那服务提供者端是如何知道TransactionContext的啊

**Comment by wanghhao** [comment]
ROOT和consumer是一个进程，provider在另外一个进程。
transactionContext 是consumer被拦截后放进去的。
