### ISSUE TITLE
事例说明中，分布式事务要是失败的话，cancel阶段是不是应该恢复订单状态为DRAFT？

### ISSUE THREAD

**Issue by daifengwei** [changmingxie/tcc-transaction#60]
个人认为，在cancel阶段和commit阶段，都不应该再发生数据状态变化的的操作，包括CONFIRM阶段订单支付服务将订单状态变成CONFIRMED,cancel阶段订单支付服务将订单状态变成PAY_FAILED等。
如果commit阶段，需要增加收款方余额，并通知收款方等操作，也应该是在一个新的分布式事务里完成。这个新事务最好是独立的，而不是嵌套事务。

上述是基于分布式事务理论的结论，实际中是不是这样不清楚。
希望楼主能够解答。谢谢。

**Comment by changmingxie** [comment]
@daifengwei 具体业务逻辑 可根据你的业务来定哈。
