### ISSUE TITLE
补偿型tcc事务中，如果补偿操作发生失败或部分失败，该如何保证数据一致性呢？

### ISSUE THREAD

**Issue by daifengwei** [changmingxie/tcc-transaction#61]
jta/xa等是通过事务管理器实现要么操作全部成功commit，要么操作全部失败rollback，来确保数据一致性的。

补偿型tcc事务中，如果补偿操作发生失败或部分失败，该如何保证数据一致性呢？

**Comment by changmingxie** [comment]
@daifengwei 会自动重试，策略可配置
