### ISSUE TITLE
极端的断电情况，刚好出现在confirm上，还是会出现异常数据的吧

### ISSUE THREAD

**Issue by a466350665** [changmingxie/tcc-transaction#64]
笔者，你好！比如说在调用RedPacketTradeOrderServiceImpl的confirmRecord方法时断电，这个点订单状态就已经被更新成功了，账户余额也被减掉，但红包金额未减

**Comment by changmingxie** [comment]
@a466350665 框架会重试，保证最终一致性。

**Comment by shipengyan** [comment]
@changmingxie 是在哪一部分

**Comment by stackvoid** [comment]
@shipengyan TransactionRecovery.class  了解一下
