### ISSUE TITLE
为什么tcc库里面一条记录也没有生成？

### ISSUE THREAD

**Issue by smallbee** [changmingxie/tcc-transaction#66]
你好，按照格式搭建了环境，demo能跑通，为什么tcc的库里面没有数据？

**Comment by changmingxie** [comment]
@smallbee tcc的日志是事务完成了日志就删除了的。

**Comment by jrz1717** [comment]
完成后是否删除事务日志，可以配置吗？

**Comment by wm3418925** [comment]
commit 或 cance执行完毕, 会删除事务信息, 如果不想删除需要修改源代码, 增加一个事务状态, 并设置成它

**Comment by chenzqcju** [comment]
@wm3418925 要修改源码哪里呢？并增加一个什么的事务状态呢？
