### ISSUE TITLE
tcc高并发的问题

### ISSUE THREAD

**Issue by qinhaiyu** [changmingxie/tcc-transaction#67]
你好，这个支持高并发的情况吗？ 如果支持的需要特殊设置吗？怎么使用，谢谢！

**Comment by changmingxie** [comment]
@qinhaiyu  系统不需要特殊配置，如果要支持高并发，那存储事务日志的库也得性能高，TransactionRepository目前支持多种存储实现，也可以自己TransactionRepository接口来适配自己的日志存储。
