### ISSUE TITLE
可以建一个讨论群吗？微信qq 都可以。

### ISSUE THREAD

**Issue by qinhaiyu** [changmingxie/tcc-transaction#68]

**Comment by changmingxie** [comment]
可加微信 changmingxie，为便于识别，麻烦在备注中写下 在tcc-transaction中声明一个tcc的方法时需要加的注解类的名字。

**Comment by TalkIsCheapGiveMeMoney** [comment]
大家可以加137216089 交流一下使用经验 新建的

**Comment by shijiaoming** [comment]
@changmingxie 最好能有个qq群，和大家一起交流，大家之间也能互相解决问题。
