### ISSUE TITLE
采用JDBC方式登记Transaction库表记录的时候没有提交数据库事务

### ISSUE THREAD

**Issue by kixiong** [changmingxie/tcc-transaction#7]
代码里面没有显式的提交数据库事务，如果数据库连接池的连接不是每条sql自动提交数据库事务的话，直接关闭数据库连接，登记的记录可能存在没有提交数据库事务。

**Comment by changmingxie** [comment]
@kixiong 
如果事务日志没有成功提交，那么整个TCC事务将会需要恢复，如果是在CONFIRMING阶段出异常，则恢复Job将继续启动事务的Confirm操作过程，如果是在TRYING阶段出异常，则恢复Job将启动事务的Cancel操作过程。
