### ISSUE TITLE
try方法执行中, 修改的参数不保存的问题

### ISSUE THREAD

**Issue by wm3418925** [changmingxie/tcc-transaction#72]
参数会在transaction commit的时候保存
获取 Transaction 先从 缓存再从 Repository
tcc-transaction 会在方法执行前保存方法参数 到 Repository和缓存
如果方法执行过程中修改了参数, 不会立即保存, 除非执行commit或cancel方法

如果调用的接口有两个provider, 第一次调用第一个, 第二次调用第二个
那么第二次就不能获取到第一次在方法内部修改过的参数

所以我在
org.mengyun.tcctransaction.interceptor.ResourceCoordinatorInterceptor
类里面加上一个方法:
`// 强制将 Transaction 存入 Repository

public boolean flushTransactionToRepository() {
    Transaction transaction = transactionConfigurator.getTransactionManager().getCurrentTransaction();
    if (null == transaction)
        return false;
    TransactionRepository transactionRepository = transactionConfigurator.getTransactionRepository();
    transactionRepository.update(transaction);
    return true;
}`

测试代码如下
`@Autowired
    private ResourceCoordinatorInterceptor resourceCoordinatorInterceptor;

    @Override
    @Transactional
    @Compensable(confirmMethod = "confirmReserveCount", cancelMethod = "cancelReserveCount")
    public void tryReserveCount(TransactionContext transactionContext, Integer storeId, Integer count) {
        // invoke service
        transactionContext.getAttachments().put("reserveCount", String.valueOf(count));
        resourceCoordinatorInterceptor.flushTransactionToRepository();
    }`

**Comment by wm3418925** [comment]
另外一个方法是(我已经测试过):
1 在方法执行前 将参数序列化
2 方法执行后(异常也要捕获), 再序列化一次
3 比较序列化的 byte[] , 不相等说明修改了, 那么更新 Transaction 到 Repository
4 抛出方法的异常 或 返回方法的返回值

**Comment by qiaofazhan** [comment]
666
