### ISSUE TITLE
tcc 事务失败，除了自动重试外，还有自动回滚吗？

### ISSUE THREAD

**Issue by jrz1717** [changmingxie/tcc-transaction#73]
tcc 事务失败，除了自动重试外，还有自动回滚吗？

**Comment by wm3418925** [comment]
commit 或 cance执行完毕, 会删除事务信息, 如果不想删除需要修改代码

**Comment by wm3418925** [comment]
try阶段执行完毕, root节点执行了commit, 那么所有节点将进入 commit阶段
commit失败会重试
如果try阶段实行失败, 所有paticipate会进入cancel, 失败后会重试

**Comment by jrz1717** [comment]
如果 commit失败重试 都失败的话，怎么办？

**Comment by bbaiggey** [comment]
重试，有个最大次数可以自己配置  重试次数达到上限 实在不行 就人工干预

**Comment by ZZMarquis** [comment]
TCC就是补偿型分布式事务啊，回滚策略需要你们根据自己的具体情况定，并且在Cancel阶段自己写代码实现（Cancel阶段其实就是补偿阶段）。
