### ISSUE TITLE
您好，建议各个sql建表语句加上comment 

### ISSUE THREAD

**Issue by cullenx** [changmingxie/tcc-transaction#76]
您好，建议各个sql建表语句加上comment，便于理解，谢谢！

**Comment by maxuyang** [comment]
问下 有一个文件叫db.sql 请问这个里面的sql 语句建立在哪个数据库里面

**Comment by cullenx** [comment]
具体哪个sql文件？  sample代码里 没有sql 头部 都是创建数据库语句

**Comment by maxuyang** [comment]
我用的是1.2的 里面有个叫db.sql 其他的都是create开头的 你可以看下 还有一个问题 改properties 文件里面有个叫 jdbc:mysql://127.0.0.1:3306/XIMA_TCC 这个的数据库 貌似配置文件里面没有

**Comment by cullenx** [comment]
sorry I don't know . please ask the others.

**Comment by changmingxie** [comment]
@maxuyang db.sql可以忽略，是TCC_TRANSACTION表创建语句。
