### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by maxy19** [changmingxie/tcc-transaction#77]
我用的是1.2的 里面有个叫db.sql 其他的都是create开头的 你可以看下 还有一个问题 改properties 文件里面有个叫 jdbc:mysql://127.0.0.1:3306/XIMA_TCC 这个的数据库 貌似配置文件里面没有

**Comment by changmingxie** [comment]
@maxuyang 可拉取看看最新的1.2代码。
