### ISSUE TITLE
支持springcloud吗

### ISSUE THREAD

**Issue by forezp** [changmingxie/tcc-transaction#82]

**Comment by changmingxie** [comment]
@forezp 不依赖底层rpc框架，可以看看sample.

**Comment by forezp** [comment]
很好，很强大，我学习下。

**Comment by bbaiggey** [comment]
tcc-transaction不和底层使用的rpc框架耦合，也就是使用doubbo,thrift,web service,http等都可

**Comment by stackvoid** [comment]
@forezp 通过切面获取到本次Request，在 Request里加上 序列化的Transaction即可；接收事务方截取即可。
