### ISSUE TITLE
为什么tcc事务切面中对乐观锁与socket超时异常不做回滚处理，只抛异常？

### ISSUE THREAD

**Issue by xll545047865** [changmingxie/tcc-transaction#87]
`
transaction = transactionManager.begin();

            try {
                returnValue = pjp.proceed();
            } catch (Throwable tryingException) {

                if (isDelayCancelException(tryingException)) {

                } else {
                    logger.warn(String.format("compensable transaction trying failed. transaction content:%s", JSON.toJSONString(transaction)), tryingException);

                    transactionManager.rollback();
                }

                throw tryingException;
            }

            transactionManager.commit();`

**Comment by changmingxie** [comment]
会回滚，会由恢复job执行回滚。

**Comment by changmingxie** [comment]
不立即回滚，主要考虑是被调用服务方存在一直在正常执行的可能，只是执行的慢，导致了调用方超时，此时如果立即回滚，在被调用方执行cancel操作的同时，被调用方的try方法还在执行，甚至cancel操作执行完了，try方法还没结束，这种情况下业务数据存在不一致的可能。目前解决办法是这类异常不立即回滚，而是由恢复job执行回滚，恢复job会在一段时间后再去调用该被调用方的cancel方法，这个时间可在RecoverConfig中设置，默认120s。
