### ISSUE TITLE
confirm/cancle框架是否已经实现幂等性，为什么demo里要强调自己实现幂等性

### ISSUE THREAD

**Issue by xll545047865** [changmingxie/tcc-transaction#89]
在调confirm及cancle方法时，如果判断事务不存在，即从未做过或已经处理完了，则直接跳过
` case CONFIRMING:
                    try {
                        transaction = transactionManager.propagationExistBegin(transactionContext);
                        transactionManager.commit();
                    } catch (NoExistedTransactionException excepton) {
                        //the transaction has been commit,ignore it.
                    }
                    break;`

**Comment by changmingxie** [comment]
@xll545047865 在confirm或是cancel时，框架是先执行服务的confirm或是cancel，执行成功后删除事务日志，这里存在服务的confirm或cancel执行完了，但是删除事务日志失败了，这种情况下恢复job将会重新执行整个confirm或是cancel，这时需要业务代码保证服务的幂等性。

**Comment by ahexian** [comment]
看了目前的demo， http服务的， 在
org.mengyun.tcctransaction.sample.http.order.service.PaymentServiceImpl
org.mengyun.tcctransaction.sample.http.capital.service.CapitalTradeOrderServiceImpl
org.mengyun.tcctransaction.sample.http.redpacket.service.RedPacketTradeOrderServiceImpl
这3个类中已经实现幂等性了,为什么作者会在特意还要强调幂等性呢？


下面是引用作者的原文:  
    如果TRY阶段正常完成，则进入CONFIRM阶段，在CONFIRM阶段（tcc-transaction自动调用）,订单支付服务将订单状态变成CONFIRMED,同时远程调用红包帐户服务和资金帐户服务对应的CONFIRM方法，将收款方的余额增加。特别说明下，由于是示例，在CONFIRM和CANCEL方法中没有实现幂等性，如果在真实项目中使用，需要保证CONFIRM和CANCEL方法的幂等性。
