### ISSUE TITLE
所有被调用的服务的方法中都需要增加一个TransactionContext参数设计上不够完美

### ISSUE THREAD

**Issue by kixiong** [changmingxie/tcc-transaction#9]
所有被调用的服务的方法中都需要增加一个TransactionContext参数设计上不够完美。
事实上，这个参数完全是TCC事务管理器自己使用的，应用并不关心这个。是否有办法让服务的方法不添加这个参数也能远程部署并使用TCC进行TCC事务管理。

**Comment by changmingxie** [comment]
有一种办法是与rpc框架集成，如与dubbo集成，让rpc框架透明地传输TransactionContext参数，但是这需要与rpc框架耦合。

**Comment by kixiong** [comment]
可以通过业务对象中的唯一键值来关联是否可行？
