### ISSUE TITLE
关于tcc-transaction的一点疑问

### ISSUE THREAD

**Issue by liangruiwei** [changmingxie/tcc-transaction#91]
楼主：
   您好，我现在用的版本是1.2.x版本，对于这个版本有几个疑问，想请教下楼主：
1。在将远程服务转化为本地方法的时候，使用了动态代理，里面远程的接口方法设置事物为SUPPORTS
在CompensableTransactionInterceptor拦截时methodType永远是root，相当于把从业务活动方的confirm和cancle方法放在了主事物的Transaction的participants里面，由主业务方统一调度，如果在执行最后一个comfirm出错了，由TransactionRecovery进行重试，这个时候原来执行成功confirm成功的又回执行一次，
是不是这个时候只需要控制服务方的接口的幂等性来防止多次调用？
2。是不是因为在生成动态代理的时候将Propagation设置为SUPPORTS，导致一直都是进不去PROVIDER这个节点，对吗？
3。关于tcc-transaction植入的问题，看了您的框架之后，发现需要同时在调用方和提供方同时引入这个框架，这个植入是不是太强了。我的理解是：只需要主业务发起方引入tcc管理器，将从业务接口提供方的try,confirm,cancel方法注入到tcc管理器，由tcc管理器统一进行调度，被调用方只需要提供try，comfirm，cancel三个接口就可以了？

**Comment by changmingxie** [comment]
@liangruiwei 
1. 在将远程服务转化为本地方法的时候，使用了动态代理，里面远程的接口方法设置事物为SUPPORTS, methodType应该不是root; 当从业务活动的confirm执行成功后，从业务活动的事务日志会删除，在恢复时如果没有事务日志，则不会再执行confirm方法，会认为已经执行成功了。
2.  没有明白您的意思？
3. 你提的也是一种思路，现有框架设计思路 保持调用方和被调用方对接简单，调用方 只需要知道被调用方的try方法就可了，无需关心被调用方的confirm和cancel方法 。

**Comment by PercyChuang** [comment]
MethodType 为root的时候，调用方报了一个错：java.lang.NoClassDefFoundError: org/mengyun/tcctransaction/interceptor/CompensableTransactionInterceptor$1 。服务端是正确的。
