### ISSUE TITLE
tcc-transaction的表既然结构一致，而且是专库，为什么不做成一张而是各系统分表？

### ISSUE THREAD

**Issue by xll545047865** [changmingxie/tcc-transaction#92]

**Comment by changmingxie** [comment]
@xll545047865 不能多个系统用同一个表，因为每个系统保存的日志有该系统中有关的类的信息，如果A的系统获取到B系统保存的日志，可能A无法解析该日志而报错。

**Comment by changmingxie** [comment]
@xll545047865 也可以将每个系统的tcc-transaction表单独建在各自系统里
