### ISSUE TITLE
demo中在主业务事务中直接远程调用从业务事务不太好吧

### ISSUE THREAD

**Issue by renshui1983** [changmingxie/tcc-transaction#93]
![tcc](https://cloud.githubusercontent.com/assets/13866684/26232613/00657688-3c8a-11e7-863a-ea454af700e9.png)

在demo中更改订单的支付状态（makePayment）是主业务事务，使用了本地事务（@Transactional）, 在方法体内又远程调用了（dubbo）红包和资金账户支付这两个从业务事务。

我们写程序时，一般都会要求本地事务方法只应包含数据库操作，避免远程访问等可能比较耗时的操作，所以我觉得上述的demo不太合理。

我想到的解决方法是增加一个外围方法，该外围方法不使用本地事务，依次调用PaymentServiceImpl.makePayment(), capitalTradeOrderService.record(), redPacketTradeOrderService.record()， 伪代码如下：

![tcc2](https://cloud.githubusercontent.com/assets/13866684/26232873/d8a8e7ae-3c8b-11e7-9fc2-9a6d9544b9ae.png)

如果有理解不对的地方，还请指教 @changmingxie 。

**Comment by changmingxie** [comment]
@renshui1983 demo只是示例，如果不想本地事务中包含远程调用，可以将@Transactional加在orderRepository.updateOrder(...)方法上。

**Comment by renshui1983** [comment]
@changmingxie  谢谢！
