### ISSUE TITLE
请问spring版本不一致怎么解决

### ISSUE THREAD

**Issue by dongchaoxue** [changmingxie/tcc-transaction#99]
本地项目spring 4.3.4.RELEASE 
启动时报：
`Caused by: java.lang.NoClassDefFoundError: org/springframework/scheduling/quartz/CronTriggerBean at org.mengyun.tcctransaction.spring.recover.RecoverScheduledJob.init(RecoverScheduledJob.java:31)`

**Comment by changmingxie** [comment]
@dongchaoxue 参考 https://github.com/changmingxie/tcc-transaction/pull/84/files

**Comment by dongchaoxue** [comment]
参考后已解决，非常感谢！！
